export const healthCourses = [
	{
		_class: "course",
		id: 1091520,
		title: "Cognitive Behavioural Therapy (CBT) Practitioner Course",
		url: "/course/cognitive-behavioural-therapy-online-course-cbt-practitioner-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 3890126,
				title: "Kain Ramsay",
				name: "Kain",
				display_name: "Kain Ramsay",
				job_title:
					"Teacher of Modern Applied Psychology & Personal Development",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/3890126_2b28_17.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/3890126_2b28_17.jpg",
				initials: "KR",
				url: "/user/kainramsay/",
			},
			{
				_class: "user",
				id: 50670208,
				title: "The Academy of Modern Applied Psychology",
				name: "The Academy of Modern",
				display_name: "The Academy of Modern Applied Psychology",
				job_title:
					"Leading the Revolution in Online Applied Psychology Training",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/50670208_47f0_7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/50670208_47f0_7.jpg",
				initials: "TA",
				url: "/user/achology-ltd/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1091520_9b90_11.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1091520_9b90_11.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1091520_9b90_11.jpg",
		published_title:
			"cognitive-behavioural-therapy-online-course-cbt-practitioner-course",
		tracking_id: "HpTLysXxTcmqCD4-yE1pNw",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"Become a Certified Cognitive Behavioural Therapy (CBT) Practitioner and elevate your understanding of human behaviour.",
		num_subscribers: 155494,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
		],
		avg_rating: 4.6353917,
		avg_rating_recent: 4.619691,
		rating: 4.619691,
		num_reviews: 33430,
		is_wishlisted: false,
		num_published_lectures: 121,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1091520_9b90_11.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1091520_9b90_11.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1091520_9b90_11.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1091520_9b90_11.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]", "Italian [Auto]"],
		created: "2017-01-26T18:33:45Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-05-31T22:54:47Z",
		objectives_summary: [
			"Cognitive psychology: An analysis, evaluation, and comparison of major ideas.",
			"The course will examine both personal characteristics and individual differences.",
			"The application of cognitive psychology to everyday events and challenges.",
		],
		is_recently_published: false,
		last_update_date: "2022-10-17",
		preview_url: "/course/1091520/preview/",
		learn_url:
			"/course/cognitive-behavioural-therapy-online-course-cbt-practitioner-course/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "31.5 total hours",
		content_info_short: "31.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "1ad68798329d4668a1ac3c7337775b49",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5124,
					display_name: "CBT Cognitive Behavioral Therapy",
					title: "CBT Cognitive Behavioral Therapy",
					topic_channel_url: "/topic/cbt/",
					url: "/topic/cbt/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "1ad68798329d4668a1ac3c7337775b49",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5124,
						display_name: "CBT Cognitive Behavioral Therapy",
						title: "CBT Cognitive Behavioral Therapy",
						topic_channel_url: "/topic/cbt/",
						url: "/topic/cbt/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5124,
				display_name: "CBT Cognitive Behavioral Therapy",
				title: "CBT Cognitive Behavioral Therapy",
				topic_channel_url: "/topic/cbt/",
				url: "/topic/cbt/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1746608,
		title: "Therapeutic Art Life Coach Certification  (Accredited)",
		url: "/course/art-therapy-life-coach-certification/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 988786,
				title: "Joeel & Natalie Rivera",
				name: "Joeel",
				display_name: "Joeel & Natalie Rivera",
				job_title: "Top instructor with over 700,000 students",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/988786_3723_6.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/988786_3723_6.jpg",
				initials: "J&",
				url: "/user/transformationservicesinc/",
			},
			{
				_class: "user",
				id: 49882118,
				title: "Victoria Hawkins",
				name: "Victoria",
				display_name: "Victoria Hawkins",
				job_title: "Holistic Wellness Practitioner",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/49882118_22b4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/49882118_22b4.jpg",
				initials: "VH",
				url: "/user/victoria-hawkins-4/",
			},
			{
				_class: "user",
				id: 62486662,
				title: "Transformation Services",
				name: "Transformation",
				display_name: "Transformation Services",
				job_title: "International Academy of Life Coaching & Entrepreneurship",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/62486662_ccd9_5.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/62486662_ccd9_5.jpg",
				initials: "TS",
				url: "/user/transformation-academy/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1746608_d226_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1746608_d226_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1746608_d226_4.jpg",
		published_title: "art-therapy-life-coach-certification",
		tracking_id: "VIkqdgqzSMKg3vqKS-tTvg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Therapeutic Art: Help Clients Heal, Reduce Stress & Manifest Dreams with Mandalas, Affirmations, Vision Boards & More",
		num_subscribers: 50753,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
		],
		avg_rating: 4.3708134,
		avg_rating_recent: 4.366006,
		rating: 4.366006,
		num_reviews: 13709,
		is_wishlisted: false,
		num_published_lectures: 42,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1746608_d226_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1746608_d226_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1746608_d226_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1746608_d226_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Romanian [Auto]",
		],
		created: "2018-06-13T15:07:28Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-06-16T21:01:11Z",
		objectives_summary: [
			"Understand the psychology behind how to use therapeutic art to access the subconscious mind and change limiting patterns and beliefs.",
			"Use therapeutic art techniques with your clients to help them increase their happiness, manage their emotions in a positive way, and feel more confident!",
			"Use therapeutic art techniques to help your life coaching clients reduce their stress and heal emotional pain.",
		],
		is_recently_published: false,
		last_update_date: "2023-07-03",
		preview_url: "/course/1746608/preview/",
		learn_url: "/course/art-therapy-life-coach-certification/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "3.5 total hours",
		content_info_short: "3.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "b9729054f7624cb0b730c0015140fa90",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 4618,
					display_name: "Art Therapy",
					title: "Art Therapy",
					topic_channel_url: "/topic/art-therapy/",
					url: "/topic/art-therapy/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "b9729054f7624cb0b730c0015140fa90",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 4618,
						display_name: "Art Therapy",
						title: "Art Therapy",
						topic_channel_url: "/topic/art-therapy/",
						url: "/topic/art-therapy/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 4618,
				display_name: "Art Therapy",
				title: "Art Therapy",
				topic_channel_url: "/topic/art-therapy/",
				url: "/topic/art-therapy/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 985790,
		title: "Herbalism :: Introduction & Medicine Making Certificate",
		url: "/course/herbalism-medicine-making/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 13395630,
				title: "Elizabeth Heck",
				name: "Elizabeth",
				display_name: "Elizabeth Heck",
				job_title: "Top Qualified Wellness Instructor",
				image_50x50: "https://img-b.udemycdn.com/user/50x50/13395630_4754.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/13395630_4754.jpg",
				initials: "EH",
				url: "/user/elizabethheck/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/985790_5813_2.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/985790_5813_2.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/985790_5813_2.jpg",
		published_title: "herbalism-medicine-making",
		tracking_id: "gS7HrmKXTEmKZi7UoaUu4g",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Take charge of your health with herbal medicine. Using herbs and natural holistic medicine is easy, effective and safe.",
		num_subscribers: 65324,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
		],
		avg_rating: 4.7233253,
		avg_rating_recent: 4.7251716,
		rating: 4.7251716,
		num_reviews: 13267,
		is_wishlisted: false,
		num_published_lectures: 75,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/985790_5813_2.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/985790_5813_2.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/985790_5813_2.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/985790_5813_2.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English", "Italian [Auto]", "Polish [Auto]"],
		created: "2016-10-16T13:15:43Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2016-10-27T19:28:05Z",
		objectives_summary: [
			"Start making your first herbal remedy from day one. It is easier than you think!",
			"Learn life-changing skills. The course has everything you need to know in one place including information you will not find anywhere else.",
			"Details of over 20 of the most important plants used in herbal medicine plus making tinctures, teas, oils, salves, honeys, syrups, compresses and poultices.",
		],
		is_recently_published: false,
		last_update_date: "2023-06-20",
		preview_url: "/course/985790/preview/",
		learn_url: "/course/herbalism-medicine-making/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "4 total hours",
		content_info_short: "4 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "2d6a2e8ae18642a6be4c6cc7e8d0b326",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6088,
					display_name: "Herbalism",
					title: "Herbalism",
					topic_channel_url: "/topic/herbalism/",
					url: "/topic/herbalism/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "2d6a2e8ae18642a6be4c6cc7e8d0b326",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6088,
						display_name: "Herbalism",
						title: "Herbalism",
						topic_channel_url: "/topic/herbalism/",
						url: "/topic/herbalism/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6088,
				display_name: "Herbalism",
				title: "Herbalism",
				topic_channel_url: "/topic/herbalism/",
				url: "/topic/herbalism/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1504862,
		title: "Internationally Accredited Certificate in Nutrition",
		url: "/course/internationally-accredited-diploma-certificate-in-nutrition/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 22973584,
				title: "Akash Sehrawat",
				name: "Akash",
				display_name: "Akash Sehrawat",
				job_title:
					"Fabulousbody Founder & International Best-Selling Instructor",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/22973584_f602_5.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/22973584_f602_5.jpg",
				initials: "AS",
				url: "/user/6138c2a9-6dd4-4d06-9e04-7de7eec703df/",
			},
			{
				_class: "user",
				id: 82467986,
				title: "Fabulous Body",
				name: "Fabulous",
				display_name: "Fabulous Body",
				job_title:
					"Educating & Empowering the World through Courses & Articles",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/82467986_96b0.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/82467986_96b0.jpg",
				initials: "FB",
				url: "/user/fabulous-body2/",
			},
			{
				_class: "user",
				id: 82470196,
				title: "Teaching Assistant",
				name: "Teaching",
				display_name: "Teaching Assistant",
				job_title: "",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/anonymous_3.png",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/anonymous_3.png",
				initials: "TA",
				url: "/user/teaching-assistant-3/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1504862_475f_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1504862_475f_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1504862_475f_4.jpg",
		published_title:
			"internationally-accredited-diploma-certificate-in-nutrition",
		tracking_id: "SPJ4jijqRI6vmMIOueaDeg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline: "Learn the Fundamentals of Nutrition Science",
		num_subscribers: 57121,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
		],
		avg_rating: 4.4744897,
		avg_rating_recent: 4.4824967,
		rating: 4.4824967,
		num_reviews: 10891,
		is_wishlisted: false,
		num_published_lectures: 98,
		num_published_practice_tests: 1,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1504862_475f_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1504862_475f_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1504862_475f_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1504862_475f_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]", "Italian [Auto]", "Polish [Auto]"],
		created: "2018-01-11T09:13:34Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 50,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-01-18T15:05:20Z",
		objectives_summary: [
			"Understand what the Macronutrients are and the role they play in our bodies",
			"Understand the role Micronutrients, Fiber, Probiotics & Water play in our bodies",
			"Understand Energy Balance. Figure out easy ways to determine BMR, TDEE",
		],
		is_recently_published: false,
		last_update_date: "2023-01-14",
		preview_url: "/course/1504862/preview/",
		learn_url:
			"/course/internationally-accredited-diploma-certificate-in-nutrition/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "5 total hours",
		content_info_short: "5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6952,
				display_name: "Nutrition",
				title: "Nutrition",
				topic_channel_url: "/topic/nutrition/",
				url: "/topic/nutrition/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 395170,
		title: "15 Minutes x 15 Days Yoga Mobility Challenge",
		url: "/course/yoga-mobility-challenge-15-minutes-x-15-days-66/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 353874,
				title: "Abi Carver",
				name: "Abi",
				display_name: "Abi Carver",
				job_title: "Yoga Alliance Certified Instructor & NASM Personal Trainer",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/353874_c05a.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/353874_c05a.jpg",
				initials: "AC",
				url: "/user/abicarver/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/395170_6eda_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/395170_6eda_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/395170_6eda_3.jpg",
		published_title: "yoga-mobility-challenge-15-minutes-x-15-days-66",
		tracking_id: "jQtetamLTBqm7K2ODqSHGw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Increase your flexibility and range of motion, energise your body and improve your yoga skills in 15 minutes a day.",
		num_subscribers: 25517,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
		],
		avg_rating: 4.6426425,
		avg_rating_recent: 4.6563754,
		rating: 4.6563754,
		num_reviews: 10664,
		is_wishlisted: false,
		num_published_lectures: 15,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/395170_6eda_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/395170_6eda_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/395170_6eda_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/395170_6eda_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"Français [Aut.]",
			"Anglais [Aut.]",
			"Allemand [Aut.]",
			"Espagnol [Aut.]",
			"Indonésien [Aut.]",
			"Italien [Aut.]",
			"Portugais [Aut.]",
		],
		created: "2015-01-15T20:07:04Z",
		instructional_level: "Intermediate Level",
		instructional_level_simple: "Intermediate",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2015-01-22T22:27:46Z",
		objectives_summary: [
			'15 vinyasa or "flow" yoga sequences.',
			"Improve your range of motion.",
			"Lubricate your joints.",
		],
		is_recently_published: false,
		last_update_date: "2022-08-26",
		preview_url: "/course/395170/preview/",
		learn_url: "/course/yoga-mobility-challenge-15-minutes-x-15-days-66/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "4 total hours",
		content_info_short: "4 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 8516,
				display_name: "Yoga",
				title: "Yoga",
				topic_channel_url: "/topic/yoga/",
				url: "/topic/yoga/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1754344,
		title: "Complete Fitness Trainer Certification: Beginner To Advanced",
		url: "/course/complete-fitness-trainer-certification-beginner-to-advanced/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 26801218,
				title: "Felix Harder",
				name: "Felix",
				display_name: "Felix Harder",
				job_title: "Health & Fitness Coach | Best Selling Instructor",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/26801218_cefd_3.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/26801218_cefd_3.jpg",
				initials: "FH",
				url: "/user/felix-harder/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1754344_cbff.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/1754344_cbff.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/1754344_cbff.jpg",
		published_title:
			"complete-fitness-trainer-certification-beginner-to-advanced",
		tracking_id: "ZWDcf31BQJKwXmVstg4XEg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Become A Fitness Coach: Create Muscle Growth & Fat Loss Workouts, Build A Fitness Training Business & Be A Health Expert",
		num_subscribers: 36774,
		caption_locales: [
			{
				_class: "locale",
				locale: "ar_AR",
				title: "العربية",
				english_title: "Arabic",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.605381,
		avg_rating_recent: 4.6211357,
		rating: 4.6211357,
		num_reviews: 8881,
		is_wishlisted: false,
		num_published_lectures: 62,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1754344_cbff.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/1754344_cbff.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/1754344_cbff.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/1754344_cbff.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Arabic [Auto]",
			"French [Auto]",
			"Italian [Auto]",
			"Simplified Chinese [Auto]",
		],
		created: "2018-06-18T15:05:12Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-06-27T18:32:05Z",
		objectives_summary: [
			"Earn your CPD Certificate",
			"Help others lose fat & build muscle",
			"Assess clients and determine fitness & strength levels",
		],
		is_recently_published: false,
		last_update_date: "2023-03-29",
		preview_url: "/course/1754344/preview/",
		learn_url:
			"/course/complete-fitness-trainer-certification-beginner-to-advanced/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "3 total hours",
		content_info_short: "3 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "2f95498609544f68a0cbc80f04f7ea7f",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5826,
					display_name: "Fitness",
					title: "Fitness",
					topic_channel_url: "/topic/fitness/",
					url: "/topic/fitness/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "2f95498609544f68a0cbc80f04f7ea7f",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5826,
						display_name: "Fitness",
						title: "Fitness",
						topic_channel_url: "/topic/fitness/",
						url: "/topic/fitness/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5826,
				display_name: "Fitness",
				title: "Fitness",
				topic_channel_url: "/topic/fitness/",
				url: "/topic/fitness/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 430228,
		title: "Sit Less, Move More - Promote Posture, Flexibility In Office",
		url: "/course/sit-less-move-more-office-desk-exercise-to-improve-posture/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 7009550,
				title: "Dr. Paula Moore",
				name: "Dr. Paula",
				display_name: "Dr. Paula Moore",
				job_title: "Top-Rated Instructor, 250,000+ Students",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/7009550_30c7_10.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/7009550_30c7_10.jpg",
				initials: "DM",
				url: "/user/posturevideos/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/430228_26e5_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/430228_26e5_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/430228_26e5_3.jpg",
		published_title:
			"sit-less-move-more-office-desk-exercise-to-improve-posture",
		tracking_id: "4PK5XqITSpOCX9BD7Sny2Q",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Avoid the dangers of prolonged sitting and boost energy and productivity. Posture and Flexibility Masterclass",
		num_subscribers: 20975,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
		],
		avg_rating: 4.575641,
		avg_rating_recent: 4.582685,
		rating: 4.582685,
		num_reviews: 8547,
		is_wishlisted: false,
		num_published_lectures: 46,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/430228_26e5_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/430228_26e5_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/430228_26e5_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/430228_26e5_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]"],
		created: "2015-02-23T19:33:21Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2015-06-19T22:42:21Z",
		objectives_summary: [
			"Learn active sitting techniques to help improve posture and reduce the risk of musculoskeletal problems that can be caused by sitting for long periods of time",
			"Incorporate 5 office exercise routines to improve your posture, and stay active and healthy even while working in an office environment",
			"Release nagging neck tension and improve your overall comfort and well-being",
		],
		is_recently_published: false,
		last_update_date: "2022-08-04",
		preview_url: "/course/430228/preview/",
		learn_url:
			"/course/sit-less-move-more-office-desk-exercise-to-improve-posture/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "2.5 total hours",
		content_info_short: "2.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7262,
				display_name: "Posture",
				title: "Posture",
				topic_channel_url: "/topic/posture/",
				url: "/topic/posture/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 2027448,
		title: 'The No. 1 Breathwork & Meditation course | "Breath is Life"',
		url: "/course/breathing/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 52872604,
				title: "Michaël Bijker",
				name: "Michaël",
				display_name: "Michaël Bijker",
				job_title: 'Founder of "Life Awareness Project" - yogalap',
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/52872604_6edc_3.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/52872604_6edc_3.jpg",
				initials: "MB",
				url: "/user/michael-bijker/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/2027448_0785_6.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/2027448_0785_6.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/2027448_0785_6.jpg",
		published_title: "breathing",
		tracking_id: "elcLg0hFR06EOKuSLMKcgQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Tap into the power of your breath and develop health, happiness and inner richness. A complete breathwork course.",
		num_subscribers: 37986,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.639138,
		avg_rating_recent: 4.648969,
		rating: 4.648969,
		num_reviews: 8330,
		is_wishlisted: false,
		num_published_lectures: 80,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/2027448_0785_6.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/2027448_0785_6.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/2027448_0785_6.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/2027448_0785_6.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]", "Simplified Chinese [Auto]"],
		created: "2018-11-15T09:03:27Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-11-22T19:31:51Z",
		objectives_summary: [
			"Learn to use the breath to relax, focus and bring health and vitality in your life. Use the breath as a tool to become a master of mind and body",
			"Learn basic and advanced breathwork and meditation techniques. Tap into the power of your breath!",
		],
		is_recently_published: false,
		last_update_date: "2022-11-24",
		preview_url: "/course/2027448/preview/",
		learn_url: "/course/breathing/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "18.5 total hours",
		content_info_short: "18.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "230dffdc06dd445fbfa84f469faab60f",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 4842,
					display_name: "Breathing Techniques",
					title: "Breathing Techniques",
					topic_channel_url: "/topic/breathing-techniques/",
					url: "/topic/breathing-techniques/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "230dffdc06dd445fbfa84f469faab60f",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 4842,
						display_name: "Breathing Techniques",
						title: "Breathing Techniques",
						topic_channel_url: "/topic/breathing-techniques/",
						url: "/topic/breathing-techniques/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 4842,
				display_name: "Breathing Techniques",
				title: "Breathing Techniques",
				topic_channel_url: "/topic/breathing-techniques/",
				url: "/topic/breathing-techniques/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1815870,
		title: "Diet And Nutrition Coach Certification: Beginner To Advanced",
		url: "/course/diet-nutrition-coach-certification-beginner-to-advanced/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 26801218,
				title: "Felix Harder",
				name: "Felix",
				display_name: "Felix Harder",
				job_title: "Health & Fitness Coach | Best Selling Instructor",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/26801218_cefd_3.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/26801218_cefd_3.jpg",
				initials: "FH",
				url: "/user/felix-harder/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1815870_476b.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/1815870_476b.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/1815870_476b.jpg",
		published_title: "diet-nutrition-coach-certification-beginner-to-advanced",
		tracking_id: "hfpYmUQ7QSumklE7SIw_CA",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Become A Nutrition Coach: Create Muscle Growth & Fat Loss Meal Plans, Build A Fitness Diet Business & Be A Health Expert",
		num_subscribers: 28730,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
		],
		avg_rating: 4.626623,
		avg_rating_recent: 4.6119823,
		rating: 4.6119823,
		num_reviews: 7419,
		is_wishlisted: false,
		num_published_lectures: 105,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1815870_476b.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/1815870_476b.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/1815870_476b.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/1815870_476b.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]"],
		created: "2018-07-23T21:00:37Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-08-27T23:47:55Z",
		objectives_summary: [
			"Earn your CPD Certificate",
			"Design weight loss & muscle growth diets",
			"Help others lose fat & build muscle",
		],
		is_recently_published: false,
		last_update_date: "2023-01-15",
		preview_url: "/course/1815870/preview/",
		learn_url:
			"/course/diet-nutrition-coach-certification-beginner-to-advanced/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "5 total hours",
		content_info_short: "5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "83ef77f19c7344189a29b8fba128f402",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6952,
					display_name: "Nutrition",
					title: "Nutrition",
					topic_channel_url: "/topic/nutrition/",
					url: "/topic/nutrition/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "83ef77f19c7344189a29b8fba128f402",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6952,
						display_name: "Nutrition",
						title: "Nutrition",
						topic_channel_url: "/topic/nutrition/",
						url: "/topic/nutrition/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6952,
				display_name: "Nutrition",
				title: "Nutrition",
				topic_channel_url: "/topic/nutrition/",
				url: "/topic/nutrition/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1289968,
		title: "Nutrition Masterclass: Build Your Perfect Diet & Meal Plan",
		url: "/course/nutrition-masterclass-build-your-perfect-diet-meal-plan/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 26801218,
				title: "Felix Harder",
				name: "Felix",
				display_name: "Felix Harder",
				job_title: "Health & Fitness Coach | Best Selling Instructor",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/26801218_cefd_3.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/26801218_cefd_3.jpg",
				initials: "FH",
				url: "/user/felix-harder/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1289968_6b08_2.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1289968_6b08_2.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1289968_6b08_2.jpg",
		published_title: "nutrition-masterclass-build-your-perfect-diet-meal-plan",
		tracking_id: "bD9DGbSvQnetFPuEDSNqlQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Learn The Truth About Nutrition, Dieting For Weight Loss, Building Muscle, Healthy Eating, Meal Planning, Fat Loss",
		num_subscribers: 44338,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5895195,
		avg_rating_recent: 4.5909433,
		rating: 4.5909433,
		num_reviews: 6848,
		is_wishlisted: false,
		num_published_lectures: 94,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1289968_6b08_2.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1289968_6b08_2.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1289968_6b08_2.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1289968_6b08_2.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"French [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Simplified Chinese [Auto]",
			"Thai [Auto]",
		],
		created: "2017-07-12T23:36:38Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-07-21T00:07:15Z",
		objectives_summary: [
			"Understand the fundamentals of healthy dieting (calories, protein, carbs, fat, vitamins & minerals)",
			"Create a diet that is perfect for your needs and lifestyle",
			"Learn when, what and how much you should eat for optimal body composition",
		],
		is_recently_published: false,
		last_update_date: "2022-12-30",
		preview_url: "/course/1289968/preview/",
		learn_url:
			"/course/nutrition-masterclass-build-your-perfect-diet-meal-plan/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "4 total hours",
		content_info_short: "4 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "83556e6aa8674995996913c6b453bfb5",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5412,
					display_name: "Dieting",
					title: "Dieting",
					topic_channel_url: "/topic/dieting/",
					url: "/topic/dieting/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "83556e6aa8674995996913c6b453bfb5",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5412,
						display_name: "Dieting",
						title: "Dieting",
						topic_channel_url: "/topic/dieting/",
						url: "/topic/dieting/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6952,
				display_name: "Nutrition",
				title: "Nutrition",
				topic_channel_url: "/topic/nutrition/",
				url: "/topic/nutrition/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 2709124,
		title: "Kids Yoga Teacher Training Certificate Course - Ages 2-17",
		url: "/course/kids-yoga-teacher-training-certificate-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 90363296,
				title: "Jessica Fleming",
				name: "Jessica",
				display_name: "Jessica Fleming",
				job_title: "Yoga Teacher Trainer",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/90363296_d134_6.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/90363296_d134_6.jpg",
				initials: "JF",
				url: "/user/jessica-fleming-13/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/2709124_745b_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/2709124_745b_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/2709124_745b_3.jpg",
		published_title: "kids-yoga-teacher-training-certificate-course",
		tracking_id: "Q0v2PpacTzyfe5tCbcUXiw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Confidently teach fun, safe and engaging yoga classes to kids aged 2 to 17 years - Kids Yoga Business Training included!",
		num_subscribers: 21708,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
		],
		avg_rating: 4.6666665,
		avg_rating_recent: 4.669409,
		rating: 4.669409,
		num_reviews: 6503,
		is_wishlisted: false,
		num_published_lectures: 75,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/2709124_745b_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/2709124_745b_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/2709124_745b_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/2709124_745b_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]"],
		created: "2019-12-17T02:41:16Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2019-12-24T15:25:54Z",
		objectives_summary: [
			"By taking this course, you will learn, step by step, how to teach fun, engaging and safe yoga classes to children of all ages, from 2-17 years!",
			"Learn what the best yoga poses for each age group are - this course includes beautifully illustrated kids yoga pose guides for you to print out and keep!",
			"Learn the 5 steps to creating your own super fun kids yoga stories for kids aged 2-8 years",
		],
		is_recently_published: false,
		last_update_date: "2022-12-26",
		preview_url: "/course/2709124/preview/",
		learn_url: "/course/kids-yoga-teacher-training-certificate-course/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "2.5 total hours",
		content_info_short: "2.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "0b18adef2c7d44a0b5ba619eecdcd006",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 8518,
					display_name: "Yoga for Kids",
					title: "Yoga for Kids",
					topic_channel_url: "/topic/yoga-for-kids/",
					url: "/topic/yoga-for-kids/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "0b18adef2c7d44a0b5ba619eecdcd006",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 8518,
						display_name: "Yoga for Kids",
						title: "Yoga for Kids",
						topic_channel_url: "/topic/yoga-for-kids/",
						url: "/topic/yoga-for-kids/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 8518,
				display_name: "Yoga for Kids",
				title: "Yoga for Kids",
				topic_channel_url: "/topic/yoga-for-kids/",
				url: "/topic/yoga-for-kids/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1253772,
		title: "Learn Meditation Basics with Certification to Guide Others",
		url: "/course/learn-to-meditate/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 23121946,
				title: "Melissa Crowhurst",
				name: "Melissa",
				display_name: "Melissa Crowhurst",
				job_title: "Reiki Master Teacher, Inspirational Coach, Author, Speaker",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/23121946_3025_4.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/23121946_3025_4.jpg",
				initials: "MC",
				url: "/user/melissa-crowhurst/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1253772_8786_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1253772_8786_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1253772_8786_3.jpg",
		published_title: "learn-to-meditate",
		tracking_id: "Gl9bz-tLQimFawc4za4OgQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Learn meditation for stress relief, mindfulness, anxiety & more! Includes 10 guided audios & Meditation Certificate",
		num_subscribers: 28288,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.62,
		avg_rating_recent: 4.6918774,
		rating: 4.6918774,
		num_reviews: 6013,
		is_wishlisted: false,
		num_published_lectures: 40,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1253772_8786_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1253772_8786_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1253772_8786_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1253772_8786_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English",
			"Italian [Auto]",
			"Simplified Chinese [Auto]",
			"Thai [Auto]",
		],
		created: "2017-06-14T09:36:37Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-06-29T15:33:53Z",
		objectives_summary: [
			"Obtain an accredited Meditation Guide Certificate",
			"How to prepare and guide a basic meditation session for others",
			"Use the 10 provided guided meditations (MP3) for yourself and for client sessions",
		],
		is_recently_published: false,
		last_update_date: "2023-06-16",
		preview_url: "/course/1253772/preview/",
		learn_url: "/course/learn-to-meditate/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1.5 total hours",
		content_info_short: "1.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6680,
				display_name: "Meditation",
				title: "Meditation",
				topic_channel_url: "/topic/meditation/",
				url: "/topic/meditation/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1229218,
		title: "Aromatherapy- Using Essential Oils For Natural Living (5 CE)",
		url: "/course/aromatherapy-how-to-use-essential-oils-in-your-everyday-life/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 7240640,
				title: "Mark Perren-Jones",
				name: "Mark",
				display_name: "Mark Perren-Jones",
				job_title:
					"Certified Aromatherapist, Spa Owner, Masseur, 200K Students",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/7240640_bf4c_2.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/7240640_bf4c_2.jpg",
				initials: "MP",
				url: "/user/markperrenjones/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1229218_b589_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1229218_b589_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1229218_b589_3.jpg",
		published_title:
			"aromatherapy-how-to-use-essential-oils-in-your-everyday-life",
		tracking_id: "QWumUoeJQYOylQp_mAR9gQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Aromatherapy-Blend Aromatherapy Essential Oils By The Notes, Beauty Products, Cleaning Products, Balms And Scrubs !",
		num_subscribers: 25038,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
		],
		avg_rating: 4.6226416,
		avg_rating_recent: 4.6624436,
		rating: 4.6624436,
		num_reviews: 5731,
		is_wishlisted: false,
		num_published_lectures: 126,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1229218_b589_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1229218_b589_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1229218_b589_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1229218_b589_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]", "Italian [Auto]", "Polish [Auto]"],
		created: "2017-05-25T12:14:11Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-06-19T15:26:45Z",
		objectives_summary: [
			"In this aromatherapy course, you will get a Certificate of Completion when you finish this aromatherapy course from Mark personally",
			"In this aromatherapy course, you will know what the essential oils are used for, how to blend them and which essential oils you can use for different ailments",
			"In this aromatherapy course, you will know how to blend essential oils for everything from treating skin conditions to cleaning your house without chemicals",
		],
		is_recently_published: false,
		last_update_date: "2023-06-28",
		preview_url: "/course/1229218/preview/",
		learn_url:
			"/course/aromatherapy-how-to-use-essential-oils-in-your-everyday-life/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "6 total hours",
		content_info_short: "6 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "db18ea8d6d454ac8beda8f3e5f299652",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 4612,
					display_name: "Aromatherapy",
					title: "Aromatherapy",
					topic_channel_url: "/topic/aromatherapy/",
					url: "/topic/aromatherapy/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "db18ea8d6d454ac8beda8f3e5f299652",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 4612,
						display_name: "Aromatherapy",
						title: "Aromatherapy",
						topic_channel_url: "/topic/aromatherapy/",
						url: "/topic/aromatherapy/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 4612,
				display_name: "Aromatherapy",
				title: "Aromatherapy",
				topic_channel_url: "/topic/aromatherapy/",
				url: "/topic/aromatherapy/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1041352,
		title: "Elevate Your Tennis Game: Learn from Champion Andre Agassi",
		url: "/course/andreagassi/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 27915804,
				title: "Andre Agassi",
				name: "Andre",
				display_name: "Andre Agassi",
				job_title: "Former #1 World Tennis Champion",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/27915804_72af_3.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/27915804_72af_3.jpg",
				initials: "AA",
				url: "/user/andre-agassi-4/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1041352_c116.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/1041352_c116.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/1041352_c116.jpg",
		published_title: "andreagassi",
		tracking_id: "0ouxz1J5TOWKjYYia4YEkw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Level up your tennis game with the next best thing to a private lesson. Master insider secrets and a winner’s mindset.",
		num_subscribers: 21021,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
		],
		avg_rating: 4.605263,
		avg_rating_recent: 4.6144495,
		rating: 4.6144495,
		num_reviews: 5571,
		is_wishlisted: false,
		num_published_lectures: 62,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1041352_c116.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/1041352_c116.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/1041352_c116.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/1041352_c116.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English", "Polish [Auto]"],
		created: "2016-12-15T00:18:28Z",
		instructional_level: "Intermediate Level",
		instructional_level_simple: "Intermediate",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-01-27T23:14:13Z",
		objectives_summary: [
			"Learn techniques for essential swings (forehand, backhand, serve, and more)",
			"Develop game strategies to defeat your opponent",
			"Practice Andre's own drills proven to advance your game",
		],
		is_recently_published: false,
		last_update_date: "2017-01-27",
		preview_url: "/course/1041352/preview/",
		learn_url: "/course/andreagassi/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1 total hour",
		content_info_short: "1 hour",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "1be1d9f048994449951c20dedf8ac110",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 8024,
					display_name: "Tennis",
					title: "Tennis",
					topic_channel_url: "/topic/tennis/",
					url: "/topic/tennis/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "1be1d9f048994449951c20dedf8ac110",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 8024,
						display_name: "Tennis",
						title: "Tennis",
						topic_channel_url: "/topic/tennis/",
						url: "/topic/tennis/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 8024,
				display_name: "Tennis",
				title: "Tennis",
				topic_channel_url: "/topic/tennis/",
				url: "/topic/tennis/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 293170,
		title: "Isla Verde Spa Relaxation Massage Certificate Course",
		url: "/course/award-winning-isla-verde-spa-relaxation-massage-masterclass/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 7240640,
				title: "Mark Perren-Jones",
				name: "Mark",
				display_name: "Mark Perren-Jones",
				job_title:
					"Certified Aromatherapist, Spa Owner, Masseur, 200K Students",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/7240640_bf4c_2.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/7240640_bf4c_2.jpg",
				initials: "MP",
				url: "/user/markperrenjones/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/293170_2550_2.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/293170_2550_2.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/293170_2550_2.jpg",
		published_title:
			"award-winning-isla-verde-spa-relaxation-massage-masterclass",
		tracking_id: "j_3SYH5hS6CH4vP-R1XCkw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"This is a Complete Massage Course That Will Teach You Everything That You Need to Know to Give Amazing Massages",
		num_subscribers: 23237,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
		],
		avg_rating: 4.7604165,
		avg_rating_recent: 4.7471232,
		rating: 4.7471232,
		num_reviews: 5366,
		is_wishlisted: false,
		num_published_lectures: 73,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/293170_2550_2.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/293170_2550_2.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/293170_2550_2.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/293170_2550_2.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English", "Italian [Auto]", "Polish [Auto]"],
		created: "2014-09-03T13:44:17Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2014-10-21T13:54:15Z",
		objectives_summary: [
			"You will get a Certificate of Completion when you finish this massage course from Mark personally",
			"You will be able to perform our relaxation massage sequence, plus have a wealth of knowledge on other aspects of the spa business that has made us No. 1!",
			"You will understand how to perform massage using correct body mechanics",
		],
		is_recently_published: false,
		last_update_date: "2023-07-18",
		preview_url: "/course/293170/preview/",
		learn_url:
			"/course/award-winning-isla-verde-spa-relaxation-massage-masterclass/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "5.5 total hours",
		content_info_short: "5.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6636,
				display_name: "Massage",
				title: "Massage",
				topic_channel_url: "/topic/massage/",
				url: "/topic/massage/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1869864,
		title: "Health and Nutrition Life Coach Certification (Accredited)",
		url: "/course/health-and-nutrition-life-coach-certification/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 988786,
				title: "Joeel & Natalie Rivera",
				name: "Joeel",
				display_name: "Joeel & Natalie Rivera",
				job_title: "Top instructor with over 700,000 students",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/988786_3723_6.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/988786_3723_6.jpg",
				initials: "J&",
				url: "/user/transformationservicesinc/",
			},
			{
				_class: "user",
				id: 31052202,
				title: "Sanda Kruger",
				name: "Sanda",
				display_name: "Sanda Kruger",
				job_title: "Entrepreneur, Life and Health Coach, Real Estate Investor",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/31052202_39f8_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/31052202_39f8_4.jpg",
				initials: "SK",
				url: "/user/sanda-kruger/",
			},
			{
				_class: "user",
				id: 62486662,
				title: "Transformation Services",
				name: "Transformation",
				display_name: "Transformation Services",
				job_title: "International Academy of Life Coaching & Entrepreneurship",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/62486662_ccd9_5.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/62486662_ccd9_5.jpg",
				initials: "TS",
				url: "/user/transformation-academy/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1869864_bab4_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1869864_bab4_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1869864_bab4_3.jpg",
		published_title: "health-and-nutrition-life-coach-certification",
		tracking_id: "Mbp8us6fSBWcRZmbswmMZg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Life Coaching: Create a Workout &  Nutrition Plan Based on Your Clients’ Fitness, Weight Loss, Dieting & Nutrition Goals",
		num_subscribers: 21006,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
		],
		avg_rating: 4.4471545,
		avg_rating_recent: 4.4406033,
		rating: 4.4406033,
		num_reviews: 5026,
		is_wishlisted: false,
		num_published_lectures: 93,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1869864_bab4_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1869864_bab4_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1869864_bab4_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1869864_bab4_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]", "Italian [Auto]"],
		created: "2018-08-21T23:30:05Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-08-28T20:52:45Z",
		objectives_summary: [
			"Develop a step-by-step nutrition and exercise program to use with your clients",
			"Design a custom health coaching package focused on YOUR unique passions and experience",
			"Receive done-for-you assessments and proven tools and processes to use with your clients, saving you time",
		],
		is_recently_published: false,
		last_update_date: "2023-07-03",
		preview_url: "/course/1869864/preview/",
		learn_url: "/course/health-and-nutrition-life-coach-certification/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "10.5 total hours",
		content_info_short: "10.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "b503cd3eacef40c9a36111f958146ae7",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 276,
					title: "Health & Fitness",
					url: "/courses/health-and-fitness/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 155400,
					display_name: "Health Coach Training",
					title: "Health Coach Training",
					topic_channel_url: "/topic/health-coaching/",
					url: "/topic/health-coaching/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "b503cd3eacef40c9a36111f958146ae7",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 276,
						title: "Health & Fitness",
						url: "/courses/health-and-fitness/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 155400,
						display_name: "Health Coach Training",
						title: "Health Coach Training",
						topic_channel_url: "/topic/health-coaching/",
						url: "/topic/health-coaching/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 276,
				title: "Health & Fitness",
				url: "/courses/health-and-fitness/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 155400,
				display_name: "Health Coach Training",
				title: "Health Coach Training",
				topic_channel_url: "/topic/health-coaching/",
				url: "/topic/health-coaching/",
				tracking_object_type: "cl",
			},
		},
	},


];
