export const musicCourses = [
	{
		_class: "course",
		id: 238934,
		title: "Pianoforall - Incredible New Way To Learn Piano & Keyboard",
		url: "/course/pianoforall-incredible-new-way-to-learn-piano-keyboard/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 5753906,
				title: "Robin Hall",
				name: "Robin",
				display_name: "Robin Hall",
				job_title:
					"Piano Teacher (450,000 students online), Artist, Therapist,",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/5753906_1b3f_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/5753906_1b3f_4.jpg",
				initials: "RH",
				url: "/user/robinhall3/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/238934_4d81_7.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/238934_4d81_7.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/238934_4d81_7.jpg",
		published_title: "pianoforall-incredible-new-way-to-learn-piano-keyboard",
		tracking_id: "R8C2tXmMS2ivMwgB90zWoA",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Learn Piano in WEEKS not years. Play-By-Ear & learn to Read Music. Pop, Blues, Jazz, Ballads, Improvisation, Classical",
		num_subscribers: 374981,
		caption_locales: [
			{
				_class: "locale",
				locale: "bg_BG",
				title: "Български",
				english_title: "Bulgarian",
			},
			{
				_class: "locale",
				locale: "cs_CZ",
				title: "Čeština",
				english_title: "Czech",
			},
			{
				_class: "locale",
				locale: "da_DK",
				title: "Dansk",
				english_title: "Danish",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "el_GR",
				title: "Ελληνικά",
				english_title: "Greek",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "et_EE",
				title: "Eesti",
				english_title: "Estonian",
			},
			{
				_class: "locale",
				locale: "fi_FI",
				title: "Suomi",
				english_title: "Finnish",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "hu_HU",
				title: "Magyar",
				english_title: "Hungarian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "ko_KR",
				title: "한국어",
				english_title: "Korean",
			},
			{
				_class: "locale",
				locale: "lt_LT",
				title: "Lietuvių",
				english_title: "Lithuanian",
			},
			{
				_class: "locale",
				locale: "lv_LV",
				title: "Latviešu",
				english_title: "Latvian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "sk_SK",
				title: "Slovenčina",
				english_title: "Slovak",
			},
			{
				_class: "locale",
				locale: "sv_SE",
				title: "Svenska",
				english_title: "Swedish",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "uk_UA",
				title: "Українська",
				english_title: "Ukrainian",
			},
		],
		avg_rating: 4.707124,
		avg_rating_recent: 4.726782,
		rating: 4.726782,
		num_reviews: 45420,
		is_wishlisted: false,
		num_published_lectures: 426,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/238934_4d81_7.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/238934_4d81_7.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/238934_4d81_7.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/238934_4d81_7.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English",
			"Bulgarian [Auto]",
			"Czech [Auto]",
			"Danish [Auto]",
			"Dutch [Auto]",
			"Estonian [Auto]",
			"Finnish [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Greek [Auto]",
			"Hungarian [Auto]",
			"Italian [Auto]",
			"Korean [Auto]",
			"Latvian [Auto]",
			"Lithuanian [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Romanian [Auto]",
			"Slovak [Auto]",
			"Spanish [Auto]",
			"Swedish [Auto]",
			"Thai [Auto]",
			"Ukrainian [Auto]",
		],
		created: "2014-06-07T21:38:52Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2014-08-07T06:27:51Z",
		objectives_summary: [
			"Pianoforall will take complete beginners to an intermediate level in a very short space of time",
			"You get to sound like a pro right from the start",
			"You will learn the absolute basic essential techniques that will allow you to play any song in any style - by ear!",
		],
		is_recently_published: false,
		last_update_date: "2022-06-29",
		preview_url: "/course/238934/preview/",
		learn_url:
			"/course/pianoforall-incredible-new-way-to-learn-piano-keyboard/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "38.5 total hours",
		content_info_short: "38.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "6b73696b753c4fd9aedd5d9251c17410",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6442,
					display_name: "Keyboard Instrument",
					title: "Keyboard Instrument",
					topic_channel_url: "/topic/keyboard-instrument/",
					url: "/topic/keyboard-instrument/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "6b73696b753c4fd9aedd5d9251c17410",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6442,
						display_name: "Keyboard Instrument",
						title: "Keyboard Instrument",
						topic_channel_url: "/topic/keyboard-instrument/",
						url: "/topic/keyboard-instrument/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7190,
				display_name: "Piano",
				title: "Piano",
				topic_channel_url: "/topic/piano/",
				url: "/topic/piano/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 42271,
		title: "Complete Guitar Lessons System - Beginner to Advanced",
		url: "/course/complete-guitar-system-beginner-to-advanced/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 603974,
				title: "Erich Andreas",
				name: "Erich",
				display_name: "Erich Andreas",
				job_title: "#1 Guitar Lessons!  40+Years. Over 600,000 Students.",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/603974_a5c2_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/603974_a5c2_4.jpg",
				initials: "EA",
				url: "/user/erichandreas/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/42271_886a_9.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/42271_886a_9.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/42271_886a_9.jpg",
		published_title: "complete-guitar-system-beginner-to-advanced",
		tracking_id: "nF_QKAOURSmr1fznKWgRdQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"All-in-one Guitar Course, Fingerstyle Guitar, Blues Guitar, Acoustic Guitar, Electric Guitar & Fingerpicking Guitarra",
		num_subscribers: 277049,
		caption_locales: [
			{
				_class: "locale",
				locale: "ar_AR",
				title: "العربية",
				english_title: "Arabic",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "ja_JP",
				title: "日本語",
				english_title: "Japanese",
			},
			{
				_class: "locale",
				locale: "ko_KR",
				title: "한국어",
				english_title: "Korean",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.589404,
		avg_rating_recent: 4.6027145,
		rating: 4.6027145,
		num_reviews: 39540,
		is_wishlisted: false,
		num_published_lectures: 340,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/42271_886a_9.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/42271_886a_9.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/42271_886a_9.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/42271_886a_9.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Arabic [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Japanese [Auto]",
			"Korean [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
			"Turkish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2013-02-18T21:11:03Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2013-05-29T15:24:47Z",
		objectives_summary: [
			"New to Guitar? This Will be the Only Course You Will Ever Need to Take",
			"Have You Playing the Guitar in the Shortest Amount of Time While Having the Most Fun",
			"Most Logical Step-by-step Method to Play Songs and Master Chords, Scales and Guitar Theory",
		],
		is_recently_published: false,
		last_update_date: "2023-06-20",
		preview_url: "/course/42271/preview/",
		learn_url: "/course/complete-guitar-system-beginner-to-advanced/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "40 total hours",
		content_info_short: "40 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "e46d3b6a36124b8e9697c20b8a461a82",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6042,
					display_name: "Guitar",
					title: "Guitar",
					topic_channel_url: "/topic/guitar/",
					url: "/topic/guitar/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "e46d3b6a36124b8e9697c20b8a461a82",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6042,
						display_name: "Guitar",
						title: "Guitar",
						topic_channel_url: "/topic/guitar/",
						url: "/topic/guitar/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6042,
				display_name: "Guitar",
				title: "Guitar",
				topic_channel_url: "/topic/guitar/",
				url: "/topic/guitar/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 882594,
		title: "Music Theory Comprehensive Complete! (Parts 1, 2, & 3)",
		url: "/course/music-theory-complete/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 913001,
				title: "Jason Allen",
				name: "Jason",
				display_name: "Jason Allen",
				job_title: "Ph.D / Ableton Certified Trainer",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/913001_767b_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/913001_767b_4.jpg",
				initials: "JA",
				url: "/user/janthonyallen/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/882594_f8ec_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/882594_f8ec_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/882594_f8ec_4.jpg",
		published_title: "music-theory-complete",
		tracking_id: "LjNSnbcHQPieZvQoEmLh7A",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"A Complete College-Level Music Theory Curriculum. This edition of the course includes levels 1, 2, & 3.",
		num_subscribers: 105921,
		caption_locales: [
			{
				_class: "locale",
				locale: "ar_AR",
				title: "العربية",
				english_title: "Arabic",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.667102,
		avg_rating_recent: 4.6693764,
		rating: 4.6693764,
		num_reviews: 19887,
		is_wishlisted: false,
		num_published_lectures: 157,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/882594_f8ec_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/882594_f8ec_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/882594_f8ec_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/882594_f8ec_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"Türkçe [Otomatik]",
			"İngilizce [Otomatik]",
			"Almanca [Otomatik]",
			"Arapça [Otomatik]",
			"Basitleştirilmiş Çince [Otomatik]",
			"Endonezce [Otomatik]",
			"Felemenkçe [Otomatik]",
			"Fransızca [Otomatik]",
			"Lehçe [Otomatik]",
			"Portekizce [Otomatik]",
			"Rumence [Otomatik]",
			"Tayca [Otomatik]",
			"Vietnamca [Otomatik]",
			"İspanyolca [Otomatik]",
			"İtalyanca [Otomatik]",
		],
		created: "2016-06-19T22:03:37Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2016-06-21T18:48:35Z",
		objectives_summary: [
			"Read Music Using Proven Techniques",
			"Understand All the Symbols (Not Only the Notes) of a Music Score",
			"Read, Play, and Count Rhythms Accurately",
		],
		is_recently_published: false,
		last_update_date: "2023-06-22",
		preview_url: "/course/882594/preview/",
		learn_url: "/course/music-theory-complete/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "12.5 total hours",
		content_info_short: "12.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "abe19740259b4841b4903b90458d4630",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6860,
					display_name: "Music Theory",
					title: "Music Theory",
					topic_channel_url: "/topic/music-theory/",
					url: "/topic/music-theory/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "abe19740259b4841b4903b90458d4630",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6860,
						display_name: "Music Theory",
						title: "Music Theory",
						topic_channel_url: "/topic/music-theory/",
						url: "/topic/music-theory/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6860,
				display_name: "Music Theory",
				title: "Music Theory",
				topic_channel_url: "/topic/music-theory/",
				url: "/topic/music-theory/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 826876,
		title: "Music + Audio Production in Logic Pro X - The Complete Guide",
		url: "/course/music-production-in-logic-pro-x-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 13762822,
				title: "Make Pro Music",
				name: "Make Pro",
				display_name: "Make Pro Music",
				job_title: "Best-selling music and audio courses",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/13762822_c2ef_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/13762822_c2ef_4.jpg",
				initials: "MM",
				url: "/user/558d170ce780b/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/826876_4fd1_6.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/826876_4fd1_6.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/826876_4fd1_6.jpg",
		published_title: "music-production-in-logic-pro-x-course",
		tracking_id: "GIlaImXBQVKNU823Xri65Q",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Become a master at using Logic Pro X | Understand music production | Learn to record, edit & mix audio to a pro standard",
		num_subscribers: 52636,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
		],
		avg_rating: 4.468254,
		avg_rating_recent: 4.4559326,
		rating: 4.4559326,
		num_reviews: 12586,
		is_wishlisted: false,
		num_published_lectures: 183,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/826876_4fd1_6.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/826876_4fd1_6.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/826876_4fd1_6.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/826876_4fd1_6.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"英語",
			"イタリア語 [自動]",
			"スペイン語 [自動]",
			"タイ語 [自動]",
			"フランス語 [自動]",
			"ポルトガル語 [自動]",
			"ポーランド語 [自動]",
		],
		created: "2016-04-20T08:28:34Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2016-05-23T22:52:54Z",
		objectives_summary: [
			"Learn how to record and edit audio to a professional standard in less time than any other DAW (because Logic Pro is super easy to use).",
			"Consistently produce mixes that sound clear, powerful, and professional by following my step-by-step mixing system using stock plugins.",
			"Write more music and edit more audio in less time by learning the little-known features of Logic Pro that will significantly speed up your workflow.",
		],
		is_recently_published: false,
		last_update_date: "2020-08-13",
		preview_url: "/course/826876/preview/",
		learn_url: "/course/music-production-in-logic-pro-x-course/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "40 total hours",
		content_info_short: "40 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6856,
				display_name: "Music Production",
				title: "Music Production",
				topic_channel_url: "/topic/music-production/",
				url: "/topic/music-production/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 897192,
		title: "Music Production in Logic Pro X - The Complete Course!",
		url: "/course/thecompletelogicprox/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 23566298,
				title: "Tomas George",
				name: "Tomas",
				display_name: "Tomas George",
				job_title: "Music Producer, Composer and Audio Engineer",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/23566298_e66f_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/23566298_e66f_4.jpg",
				initials: "TG",
				url: "/user/tomas-george/",
			},
			{
				_class: "user",
				id: 37215098,
				title: "Christopher Carvalho",
				name: "Christopher",
				display_name: "Christopher Carvalho",
				job_title: "Founder of Unlock Your Sound",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/37215098_cc26_6.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/37215098_cc26_6.jpg",
				initials: "CC",
				url: "/user/christopher-carvalho-5/",
			},
			{
				_class: "user",
				id: 49549822,
				title: "Ian Alexander",
				name: "Ian",
				display_name: "Ian Alexander",
				job_title: "UK Based Audio Engineer",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/49549822_3deb_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/49549822_3deb_4.jpg",
				initials: "IA",
				url: "/user/ian-richardson-12/",
			},
			{
				_class: "user",
				id: 45765646,
				title: "Digital Music Masters",
				name: "Digital Music",
				display_name: "Digital Music Masters",
				job_title: "Online Music Production Academy",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/45765646_eef7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/45765646_eef7.jpg",
				initials: "DM",
				url: "/user/digital-music-masters/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/897192_2cee_12.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/897192_2cee_12.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/897192_2cee_12.jpg",
		published_title: "thecompletelogicprox",
		tracking_id: "29p0K8iFQDyI_TTUH4CwYQ",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"Join Successful Music Production + Logic Pro X students in Creating, Recording, Mixing Music + Mastering in Logic Pro X",
		num_subscribers: 62236,
		caption_locales: [
			{
				_class: "locale",
				locale: "bg_BG",
				title: "Български",
				english_title: "Bulgarian",
			},
			{
				_class: "locale",
				locale: "cs_CZ",
				title: "Čeština",
				english_title: "Czech",
			},
			{
				_class: "locale",
				locale: "da_DK",
				title: "Dansk",
				english_title: "Danish",
			},
			{
				_class: "locale",
				locale: "el_GR",
				title: "Ελληνικά",
				english_title: "Greek",
			},
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "et_EE",
				title: "Eesti",
				english_title: "Estonian",
			},
			{
				_class: "locale",
				locale: "fi_FI",
				title: "Suomi",
				english_title: "Finnish",
			},
			{
				_class: "locale",
				locale: "hu_HU",
				title: "Magyar",
				english_title: "Hungarian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "lt_LT",
				title: "Lietuvių",
				english_title: "Lithuanian",
			},
			{
				_class: "locale",
				locale: "lv_LV",
				title: "Latviešu",
				english_title: "Latvian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "sk_SK",
				title: "Slovenčina",
				english_title: "Slovak",
			},
			{
				_class: "locale",
				locale: "sv_SE",
				title: "Svenska",
				english_title: "Swedish",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "uk_UA",
				title: "Українська",
				english_title: "Ukrainian",
			},
		],
		avg_rating: 4.757576,
		avg_rating_recent: 4.757912,
		rating: 4.757912,
		num_reviews: 12012,
		is_wishlisted: false,
		num_published_lectures: 478,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/897192_2cee_12.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/897192_2cee_12.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/897192_2cee_12.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/897192_2cee_12.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English",
			"Bulgarian [Auto]",
			"Czech [Auto]",
			"Danish [Auto]",
			"Dutch [Auto]",
			"Estonian [Auto]",
			"Finnish [Auto]",
			"Greek [Auto]",
			"Hungarian [Auto]",
			"Italian [Auto]",
			"Latvian [Auto]",
			"Lithuanian [Auto]",
			"Polish [Auto]",
			"Romanian [Auto]",
			"Slovak [Auto]",
			"Spanish [Auto]",
			"Swedish [Auto]",
			"Thai [Auto]",
			"Ukrainian [Auto]",
		],
		created: "2016-07-05T22:01:21Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2016-08-03T16:43:42Z",
		objectives_summary: [
			"Learn how to set-up and navigate around Logic Pro X so you can learn to use this amazing piece of softare",
			"Import and search Apple Loops to easily help you create you own music",
			"Be able to record and edit MIDI Information easily and Quickly in Logic Pro X",
		],
		is_recently_published: false,
		last_update_date: "2023-07-02",
		preview_url: "/course/897192/preview/",
		learn_url: "/course/thecompletelogicprox/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "51 total hours",
		content_info_short: "51 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "7bddf74a93414cad90c465572d60289a",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6856,
					display_name: "Music Production",
					title: "Music Production",
					topic_channel_url: "/topic/music-production/",
					url: "/topic/music-production/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "7bddf74a93414cad90c465572d60289a",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6856,
						display_name: "Music Production",
						title: "Music Production",
						topic_channel_url: "/topic/music-production/",
						url: "/topic/music-production/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 16474,
				display_name: "Logic Pro",
				title: "Logic Pro",
				topic_channel_url: "/topic/logic-pro-x/",
				url: "/topic/logic-pro-x/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1147828,
		title: "Music Theory for Electronic Music COMPLETE: Parts 1, 2, & 3",
		url: "/course/music-theory-for-electronic-music-complete-parts-1-2-3/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 913001,
				title: "Jason Allen",
				name: "Jason",
				display_name: "Jason Allen",
				job_title: "Ph.D / Ableton Certified Trainer",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/913001_767b_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/913001_767b_4.jpg",
				initials: "JA",
				url: "/user/janthonyallen/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1147828_0474_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1147828_0474_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1147828_0474_3.jpg",
		published_title: "music-theory-for-electronic-music-complete-parts-1-2-3",
		tracking_id: "KHfvQJ7HTC-fQ7WSCUKnrQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Electronic music theory, digital music theory, and dance music theory. Learn music theory with ableton live and more!",
		num_subscribers: 47110,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
		],
		avg_rating: 4.622807,
		avg_rating_recent: 4.5984945,
		rating: 4.5984945,
		num_reviews: 8270,
		is_wishlisted: false,
		num_published_lectures: 126,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1147828_0474_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1147828_0474_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1147828_0474_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1147828_0474_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Romanian [Auto]",
			"Thai [Auto]",
		],
		created: "2017-03-16T15:25:18Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-03-18T00:56:45Z",
		objectives_summary: [
			"By the end of this course, you will have improved your tracks by understanding how to build chords and melodies that work together.",
			"Understand and apply minor chords",
			"Use the circle of fifths to generate new ideas for your own tracks",
		],
		is_recently_published: false,
		last_update_date: "2023-02-27",
		preview_url: "/course/1147828/preview/",
		learn_url:
			"/course/music-theory-for-electronic-music-complete-parts-1-2-3/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "12.5 total hours",
		content_info_short: "12.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "f8ed0040fc9843969d9997d0f1cb92d3",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5578,
					display_name: "Electronic Music",
					title: "Electronic Music",
					topic_channel_url: "/topic/electronic-music/",
					url: "/topic/electronic-music/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "f8ed0040fc9843969d9997d0f1cb92d3",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5578,
						display_name: "Electronic Music",
						title: "Electronic Music",
						topic_channel_url: "/topic/electronic-music/",
						url: "/topic/electronic-music/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6860,
				display_name: "Music Theory",
				title: "Music Theory",
				topic_channel_url: "/topic/music-theory/",
				url: "/topic/music-theory/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 2018498,
		title: "FL Studio 21 - Music Production In FL Studio 21 for Mac & PC",
		url: "/course/fl-studio/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 7830052,
				title: "Martin Svensson",
				name: "Martin",
				display_name: "Martin Svensson",
				job_title: "Logic Pro X Certified Music Producer, 20 000 + Students",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/7830052_3c36_7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/7830052_3c36_7.jpg",
				initials: "MS",
				url: "/user/martin631/",
			},
			{
				_class: "user",
				id: 49660372,
				title: "Music-Prod Education",
				name: "Music-Prod",
				display_name: "Music-Prod Education",
				job_title: "Music-Prod.com - Education & Resources For Music Producers",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/49660372_d2d3_2.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/49660372_d2d3_2.jpg",
				initials: "ME",
				url: "/user/music-prod/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/2018498_268a.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/2018498_268a.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/2018498_268a.jpg",
		published_title: "fl-studio",
		tracking_id: "JrLt69WEQxez76rVisZgZg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Electronic Music Production in FL Studio - 6 Full Tracks: Music Recording, Audio Editing, Digital Audio EQ & Mastering",
		num_subscribers: 34026,
		caption_locales: [
			{
				_class: "locale",
				locale: "ar_AR",
				title: "العربية",
				english_title: "Arabic",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "ja_JP",
				title: "日本語",
				english_title: "Japanese",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.582353,
		avg_rating_recent: 4.53325,
		rating: 4.53325,
		num_reviews: 7051,
		is_wishlisted: false,
		num_published_lectures: 202,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/2018498_268a.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/2018498_268a.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/2018498_268a.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/2018498_268a.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Arabic [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"Japanese [Auto]",
			"Simplified Chinese [Auto]",
			"Thai [Auto]",
			"Turkish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2018-11-10T14:02:56Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-11-22T01:08:45Z",
		objectives_summary: [
			"Learn How To Make Music in FL Studio in Just a Day",
			"Learn How To Manage FL Studio Fast",
			"Learn Working with FL Studio in a Quick and Easy Way",
		],
		is_recently_published: false,
		last_update_date: "2023-06-22",
		preview_url: "/course/2018498/preview/",
		learn_url: "/course/fl-studio/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "28.5 total hours",
		content_info_short: "28.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5834,
				display_name: "FL Studio",
				title: "FL Studio",
				topic_channel_url: "/topic/fl-studio/",
				url: "/topic/fl-studio/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1132342,
		title: "Ultimate Beginner Guitar Masterclass",
		url: "/course/beginner-guitar-masterclass/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 12277336,
				title: "Henry Olsen",
				name: "Henry",
				display_name: "Henry Olsen",
				job_title: "Beginner Guitar Expert - 140,000 Happy Students",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/12277336_ead1_17.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/12277336_ead1_17.jpg",
				initials: "HO",
				url: "/user/henryolsen3/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1132342_48ec_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1132342_48ec_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1132342_48ec_3.jpg",
		published_title: "beginner-guitar-masterclass",
		tracking_id: "t2PRvbJ-Q4KT0M1mUwcAOw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Beginner Guitar Lessons: Learn Acoustic Guitar, Blues Guitar, Basic Fingerstyle Guitar, Guitar Chords, Guitar Technique",
		num_subscribers: 86078,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
		],
		avg_rating: 4.7135415,
		avg_rating_recent: 4.7564855,
		rating: 4.7564855,
		num_reviews: 6983,
		is_wishlisted: false,
		num_published_lectures: 134,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1132342_48ec_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1132342_48ec_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1132342_48ec_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1132342_48ec_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
		],
		created: "2017-03-02T06:56:49Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-05-15T23:04:11Z",
		objectives_summary: [
			"Learn guitar chords that will allow you to play millions of songs",
			"FREE BONUS - 42 page picture chord book included - Learn guitar chords with ease",
			"Learn to choose the right guitar for you",
		],
		is_recently_published: false,
		last_update_date: "2021-03-02",
		preview_url: "/course/1132342/preview/",
		learn_url: "/course/beginner-guitar-masterclass/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "15 total hours",
		content_info_short: "15 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6042,
				display_name: "Guitar",
				title: "Guitar",
				topic_channel_url: "/topic/guitar/",
				url: "/topic/guitar/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 200598,
		title: "Learn to play HARMONICA, the easiest instrument to pick up!",
		url: "/course/benhewlettharmonicatuitionultimate-harmonica-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 2951312,
				title: "Ben Hewlett",
				name: "Ben",
				display_name: "Ben Hewlett",
				job_title:
					"Let me turbocharge your harmonica playing to the next level",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/2951312_126e_6.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/2951312_126e_6.jpg",
				initials: "BH",
				url: "/user/benhewlett/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/200598_16d5_11.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/200598_16d5_11.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/200598_16d5_11.jpg",
		published_title: "benhewlettharmonicatuitionultimate-harmonica-course",
		tracking_id: "p3TsjixqRiKR9XLRjvPJ9g",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Ultimate diatonic harmonica lessons, blues, country music, rock; you will learn how to play on/off stage, solo/group",
		num_subscribers: 41133,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
		],
		avg_rating: 4.5694447,
		avg_rating_recent: 4.5488987,
		rating: 4.5488987,
		num_reviews: 6749,
		is_wishlisted: false,
		num_published_lectures: 244,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/200598_16d5_11.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/200598_16d5_11.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/200598_16d5_11.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/200598_16d5_11.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Romanian [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
		],
		created: "2014-04-17T09:18:05Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2014-04-27T16:25:44Z",
		objectives_summary: [
			"how to play the 12 bar blues, chords, rhythms, tone and chugging",
			"how to breathe properly, use straight and swing rhythms",
			"how to play single notes with pucker and tongue-blocked embouchures",
		],
		is_recently_published: false,
		last_update_date: "2023-02-26",
		preview_url: "/course/200598/preview/",
		learn_url:
			"/course/benhewlettharmonicatuitionultimate-harmonica-course/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "23.5 total hours",
		content_info_short: "23.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "b16f53ec90064ff98da7c6f40704a19d",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6066,
					display_name: "Harmonica",
					title: "Harmonica",
					topic_channel_url: "/topic/harmonica/",
					url: "/topic/harmonica/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "b16f53ec90064ff98da7c6f40704a19d",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6066,
						display_name: "Harmonica",
						title: "Harmonica",
						topic_channel_url: "/topic/harmonica/",
						url: "/topic/harmonica/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6066,
				display_name: "Harmonica",
				title: "Harmonica",
				topic_channel_url: "/topic/harmonica/",
				url: "/topic/harmonica/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 355662,
		title: "Read Music FAST!",
		url: "/course/sight-reading/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 9081676,
				title: "Benedict Westenra",
				name: "Benedict",
				display_name: "Benedict Westenra",
				job_title: '"The best piano teacher in London", 1,000+ 5* reviews',
				image_50x50: "https://img-c.udemycdn.com/user/50x50/9081676_c709_3.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/9081676_c709_3.jpg",
				initials: "BW",
				url: "/user/benedictwestenra/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/355662_2977_14.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/355662_2977_14.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/355662_2977_14.jpg",
		published_title: "sight-reading",
		tracking_id: "ye0jV3KNQfeViYYhScnVhg",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"Learn to read music using my unique method: just see a note on a piano score and play it on the keyboard straight away",
		num_subscribers: 27947,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.8131313,
		avg_rating_recent: 4.8024406,
		rating: 4.8024406,
		num_reviews: 6038,
		is_wishlisted: false,
		num_published_lectures: 32,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/355662_2977_14.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/355662_2977_14.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/355662_2977_14.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/355662_2977_14.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Polish [Auto]",
			"Simplified Chinese [Auto]",
		],
		created: "2014-11-24T22:03:52Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2014-12-17T19:14:06Z",
		objectives_summary: [
			"See a note on a score and play it on the piano straight away",
			"Understand how sight reading works",
			"Name any note on the piano instantly",
		],
		is_recently_published: false,
		last_update_date: "2022-05-26",
		preview_url: "/course/355662/preview/",
		learn_url: "/course/sight-reading/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1.5 total hours",
		content_info_short: "1.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "94c652ba67d34ef8b23f59f9de375215",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 7454,
					display_name: "Reading Music",
					title: "Reading Music",
					topic_channel_url: "/topic/reading-music/",
					url: "/topic/reading-music/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "94c652ba67d34ef8b23f59f9de375215",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 7454,
						display_name: "Reading Music",
						title: "Reading Music",
						topic_channel_url: "/topic/reading-music/",
						url: "/topic/reading-music/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7454,
				display_name: "Reading Music",
				title: "Reading Music",
				topic_channel_url: "/topic/reading-music/",
				url: "/topic/reading-music/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 456284,
		title: "The Professional Guitar Masterclass",
		url: "/course/the-professional-guitar-masterclass/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 3761086,
				title: "Michael Palmisano",
				name: "Michael",
				display_name: "Michael Palmisano",
				job_title: "Award Winning GIT Grad, Guitargate CEO, 15yr Working Pro.",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/3761086_b15b.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/3761086_b15b.jpg",
				initials: "MP",
				url: "/user/michaelpalmisano/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/456284_80ce_9.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/456284_80ce_9.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/456284_80ce_9.jpg",
		published_title: "the-professional-guitar-masterclass",
		tracking_id: "naBqlIEDTfad8ooE4MVTFw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Learn The Tools Used By The World's Top Professional Guitar Players.",
		num_subscribers: 52419,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
		],
		avg_rating: 4.604651,
		avg_rating_recent: 4.6050797,
		rating: 4.6050797,
		num_reviews: 5911,
		is_wishlisted: false,
		num_published_lectures: 136,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/456284_80ce_9.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/456284_80ce_9.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/456284_80ce_9.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/456284_80ce_9.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Romanian [Auto]",
		],
		created: "2015-03-24T23:53:27Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2015-04-28T17:27:26Z",
		objectives_summary: [
			"Develop your own unique voice on the guitar",
			"Understand and APPLY music theory",
			"Play any chord anywhere on the neck",
		],
		is_recently_published: false,
		last_update_date: "2017-08-28",
		preview_url: "/course/456284/preview/",
		learn_url: "/course/the-professional-guitar-masterclass/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "9.5 total hours",
		content_info_short: "9.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6042,
				display_name: "Guitar",
				title: "Guitar",
				topic_channel_url: "/topic/guitar/",
				url: "/topic/guitar/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1250174,
		title: "BECOME A GREAT SINGER: Your Complete Vocal Training System",
		url: "/course/become-a-great-singer-your-complete-vocal-training-system/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 33004532,
				title: "Robert Lunte",
				name: "Robert",
				display_name: "Robert Lunte",
				job_title: "Founder of The Vocalist Studio & courseCREEK Consulting",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/33004532_5f6b_6.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/33004532_5f6b_6.jpg",
				initials: "RL",
				url: "/user/robert-lunte/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1250174_48d9_14.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1250174_48d9_14.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1250174_48d9_14.jpg",
		published_title:
			"become-a-great-singer-your-complete-vocal-training-system",
		tracking_id: "rnc5LuJMRyKk2Ng3FyLVtQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline: "Immediately Improve Your Singing. (Any Level, Any Style)",
		num_subscribers: 59891,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
		],
		avg_rating: 4.0689654,
		avg_rating_recent: 3.9639575,
		rating: 3.9639575,
		num_reviews: 5571,
		is_wishlisted: false,
		num_published_lectures: 189,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1250174_48d9_14.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1250174_48d9_14.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1250174_48d9_14.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1250174_48d9_14.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English", "Italian [Auto]"],
		created: "2017-06-11T21:58:55Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-08-25T23:16:11Z",
		objectives_summary: [
			"The MOST Successful Singing Course on Udemy.",
			"Chris Cornell, Layne Staley, Geoff Tate and Ann Wilson all trained THESE techniques. You will be part of that legacy of training.",
			"Extend Your Vocal Range.",
		],
		is_recently_published: false,
		last_update_date: "2022-04-04",
		preview_url: "/course/1250174/preview/",
		learn_url:
			"/course/become-a-great-singer-your-complete-vocal-training-system/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "23.5 total hours",
		content_info_short: "23.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7742,
				display_name: "Singing",
				title: "Singing",
				topic_channel_url: "/topic/singing/",
				url: "/topic/singing/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1435772,
		title: "Music Production in Ableton Live 10 - The Complete Course!",
		url: "/course/abletonlive10/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 23566298,
				title: "Tomas George",
				name: "Tomas",
				display_name: "Tomas George",
				job_title: "Music Producer, Composer and Audio Engineer",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/23566298_e66f_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/23566298_e66f_4.jpg",
				initials: "TG",
				url: "/user/tomas-george/",
			},
			{
				_class: "user",
				id: 45765646,
				title: "Digital Music Masters",
				name: "Digital Music",
				display_name: "Digital Music Masters",
				job_title: "Online Music Production Academy",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/45765646_eef7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/45765646_eef7.jpg",
				initials: "DM",
				url: "/user/digital-music-masters/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1435772_8edb_6.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1435772_8edb_6.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1435772_8edb_6.jpg",
		published_title: "abletonlive10",
		tracking_id: "6gNCTwpARiq4pcgPReXX_A",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"Learn Music Production in Ableton Live 10 Today and Understand how to Create, Record and Edit Your Own Music + Live Sets",
		num_subscribers: 26343,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
		],
		avg_rating: 4.4565215,
		avg_rating_recent: 4.4233446,
		rating: 4.4233446,
		num_reviews: 5316,
		is_wishlisted: false,
		num_published_lectures: 163,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1435772_8edb_6.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1435772_8edb_6.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1435772_8edb_6.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1435772_8edb_6.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English", "Italian [Auto]", "Polish [Auto]"],
		created: "2017-11-16T17:26:21Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-02-02T16:44:10Z",
		objectives_summary: [
			"Learn how to set-up and navigate themselves around Ableton Live 10 so they can learn to use this amazing piece of music production software",
			"Record and Edit MIDI Information to create interesting beats and music",
			"Warp and Edit Audio for samples and loops",
		],
		is_recently_published: false,
		last_update_date: "2023-07-02",
		preview_url: "/course/1435772/preview/",
		learn_url: "/course/abletonlive10/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "15.5 total hours",
		content_info_short: "15.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 10158,
				display_name: "Ableton Live",
				title: "Ableton Live",
				topic_channel_url: "/topic/ableton-live/",
				url: "/topic/ableton-live/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 3626878,
		title: "Ableton Live 11 - Music Production in Ableton Live",
		url: "/course/ableton-live-11-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 23566298,
				title: "Tomas George",
				name: "Tomas",
				display_name: "Tomas George",
				job_title: "Music Producer, Composer and Audio Engineer",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/23566298_e66f_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/23566298_e66f_4.jpg",
				initials: "TG",
				url: "/user/tomas-george/",
			},
			{
				_class: "user",
				id: 49549822,
				title: "Ian Alexander",
				name: "Ian",
				display_name: "Ian Alexander",
				job_title: "UK Based Audio Engineer",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/49549822_3deb_4.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/49549822_3deb_4.jpg",
				initials: "IA",
				url: "/user/ian-richardson-12/",
			},
			{
				_class: "user",
				id: 45765646,
				title: "Digital Music Masters",
				name: "Digital Music",
				display_name: "Digital Music Masters",
				job_title: "Online Music Production Academy",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/45765646_eef7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/45765646_eef7.jpg",
				initials: "DM",
				url: "/user/digital-music-masters/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/3626878_3aa3_5.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/3626878_3aa3_5.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/3626878_3aa3_5.jpg",
		published_title: "ableton-live-11-course",
		tracking_id: "yfw4oF23QPm-Vkl8c3Dlbg",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"Learn Music Production, Recording, Editing, Music Mixing, Songwriting + Music Theory in this Ableton Live 11 Course",
		num_subscribers: 21362,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
		],
		avg_rating: 4.6873384,
		avg_rating_recent: 4.6936507,
		rating: 4.6936507,
		num_reviews: 4740,
		is_wishlisted: false,
		num_published_lectures: 210,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/3626878_3aa3_5.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/3626878_3aa3_5.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/3626878_3aa3_5.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/3626878_3aa3_5.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["Inglese"],
		created: "2020-11-10T14:37:18Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2021-02-07T15:26:28Z",
		objectives_summary: [
			"Setup and Navigate Around Ableton Live",
			"Learn how to Record MIDI",
			"Learn to Record Audio",
		],
		is_recently_published: false,
		last_update_date: "2023-07-02",
		preview_url: "/course/3626878/preview/",
		learn_url: "/course/ableton-live-11-course/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "21.5 total hours",
		content_info_short: "21.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "e5000a71efcf4b71abf72b891f0a1eb4",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 10158,
					display_name: "Ableton Live",
					title: "Ableton Live",
					topic_channel_url: "/topic/ableton-live/",
					url: "/topic/ableton-live/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "e5000a71efcf4b71abf72b891f0a1eb4",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 10158,
						display_name: "Ableton Live",
						title: "Ableton Live",
						topic_channel_url: "/topic/ableton-live/",
						url: "/topic/ableton-live/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 10158,
				display_name: "Ableton Live",
				title: "Ableton Live",
				topic_channel_url: "/topic/ableton-live/",
				url: "/topic/ableton-live/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1322444,
		title: "How to Become a DJ - Learn How to Start DJing Online Today",
		url: "/course/online-dj-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 34619352,
				title: "Ross Palmer",
				name: "Ross",
				display_name: "Ross Palmer",
				job_title: "Digital Mentor",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/34619352_8d14_8.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/34619352_8d14_8.jpg",
				initials: "RP",
				url: "/user/ross-palmer-4/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1322444_5c21.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/1322444_5c21.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/1322444_5c21.jpg",
		published_title: "online-dj-course",
		tracking_id: "RAMhnsCVRCSOYF1s1SNspA",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Professional DJ School - 11 hours of high-quality content. Former students on: Armada, Spinnin, Ultra, Revealed, & more!",
		num_subscribers: 21136,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
		],
		avg_rating: 4.6266665,
		avg_rating_recent: 4.609589,
		rating: 4.609589,
		num_reviews: 4615,
		is_wishlisted: false,
		num_published_lectures: 51,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1322444_5c21.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/1322444_5c21.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/1322444_5c21.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/1322444_5c21.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: ["English [Auto]", "Spanish [Auto]"],
		created: "2017-08-15T17:42:45Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-08-16T22:56:35Z",
		objectives_summary: [
			"How to DJ - Learn how to become a DJ online: This best-selling, top-rated online DJ school is a complete masterclass with 11 hours of high quality video.",
			"You will have EVERY skill needed to play in front of the largest crowds and win. You won't have to rely on a pre-recorded set to play like a virtuoso.",
		],
		is_recently_published: false,
		last_update_date: "2021-02-10",
		preview_url: "/course/1322444/preview/",
		learn_url: "/course/online-dj-course/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "11 total hours",
		content_info_short: "11 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5468,
				display_name: "DJ",
				title: "DJ",
				topic_channel_url: "/topic/dj/",
				url: "/topic/dj/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1516474,
		title: "SINGING SIMPLIFIED #1: The Fast-Track to Singing Like a Pro",
		url: "/course/singing-simplified/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 41487166,
				title: "Steve Glazer",
				name: "Steve",
				display_name: "Steve Glazer",
				job_title: "Musician, Songwriter, Teacher, Entrepreneur",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/41487166_a226.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/41487166_a226.jpg",
				initials: "SG",
				url: "/user/steve-glazer/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1516474_7722.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/1516474_7722.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/1516474_7722.jpg",
		published_title: "singing-simplified",
		tracking_id: "BqhT0DkgTwCC3SkNe3UKBw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Find your unique voice naturally, while having FUN doing it!  A modern approach to singing lessons & vocal training.",
		num_subscribers: 36743,
		caption_locales: [
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
		],
		avg_rating: 4.6849313,
		avg_rating_recent: 4.692406,
		rating: 4.692406,
		num_reviews: 4430,
		is_wishlisted: false,
		num_published_lectures: 57,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1516474_7722.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/1516474_7722.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/1516474_7722.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/1516474_7722.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Romanian [Auto]",
			"Thai [Auto]",
		],
		created: "2018-01-18T21:47:51Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-02-26T21:10:55Z",
		objectives_summary: [
			"You'll be able to sing with much more control, confidence, consistency, and better overall tone.",
			"You'll be able to sing much higher than you did before this course - with MUCH less strain.",
			"You'll be able to sing with much better technique - saving your voice from future damage.",
		],
		is_recently_published: false,
		last_update_date: "2023-07-20",
		preview_url: "/course/1516474/preview/",
		learn_url: "/course/singing-simplified/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "3 total hours",
		content_info_short: "3 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "f9d5d0ad2d21405cbbe142e8c9e94935",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 278,
					title: "Music",
					url: "/courses/music/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 7742,
					display_name: "Singing",
					title: "Singing",
					topic_channel_url: "/topic/singing/",
					url: "/topic/singing/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "f9d5d0ad2d21405cbbe142e8c9e94935",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 278,
						title: "Music",
						url: "/courses/music/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 7742,
						display_name: "Singing",
						title: "Singing",
						topic_channel_url: "/topic/singing/",
						url: "/topic/singing/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 278,
				title: "Music",
				url: "/courses/music/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7742,
				display_name: "Singing",
				title: "Singing",
				topic_channel_url: "/topic/singing/",
				url: "/topic/singing/",
				tracking_object_type: "cl",
			},
		},
	},
];
