export const personalCourses = [
	{
		_class: "course",
		id: 655608,
		title: "Productivity and Time Management for the Overwhelmed",
		url: "/course/productivity-and-time-management/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 9406592,
				title: "Josh Paulsen",
				name: "Josh",
				display_name: "Josh Paulsen",
				job_title: "Productivity and Goals Coach to Leaders and Entrepreneurs",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/9406592_9dcf.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/9406592_9dcf.jpg",
				initials: "JP",
				url: "/user/joshpaulsen2/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/655608_270e_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/655608_270e_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/655608_270e_4.jpg",
		published_title: "productivity-and-time-management",
		tracking_id: "e1Oo2ahdT4mbG0aD1tFFxg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"A complete productivity and time management course designed to help you reduce your overwhelm and increase your results.",
		num_subscribers: 192961,
		caption_locales: [
			{
				_class: "locale",
				locale: "ar_AR",
				title: "العربية",
				english_title: "Arabic",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "ja_JP",
				title: "日本語",
				english_title: "Japanese",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5218177,
		avg_rating_recent: 4.5053997,
		rating: 4.5053997,
		num_reviews: 67899,
		is_wishlisted: false,
		num_published_lectures: 32,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/655608_270e_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/655608_270e_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/655608_270e_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/655608_270e_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Arabic [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Japanese [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Romanian [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
			"Turkish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2015-10-30T15:09:33Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2015-11-10T22:18:22Z",
		objectives_summary: [
			"Take control of their mindset and energy levels to increase your productivity",
			"Discover why you are not as productive as you could be and develop a plan to improve",
			"Increase  your productivity by implementing new strategies throughout your day",
		],
		is_recently_published: false,
		last_update_date: "2017-06-14",
		preview_url: "/course/655608/preview/",
		learn_url: "/course/productivity-and-time-management/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "2 total hours",
		content_info_short: "2 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "c11193eccf7c4636b7595497461ee991",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 7142,
					display_name: "Personal Productivity",
					title: "Personal Productivity",
					topic_channel_url: "/topic/personal-productivity/",
					url: "/topic/personal-productivity/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "c11193eccf7c4636b7595497461ee991",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 7142,
						display_name: "Personal Productivity",
						title: "Personal Productivity",
						topic_channel_url: "/topic/personal-productivity/",
						url: "/topic/personal-productivity/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7142,
				display_name: "Personal Productivity",
				title: "Personal Productivity",
				topic_channel_url: "/topic/personal-productivity/",
				url: "/topic/personal-productivity/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 2108272,
		title: "Time Management Mastery: Do More, Stress Less",
		url: "/course/do-more-stress-less/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 61268972,
				title: "Alexis Haselberger",
				name: "Alexis",
				display_name: "Alexis Haselberger",
				job_title: "Time-Management and Productivity Coach",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/61268972_cb7d.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/61268972_cb7d.jpg",
				initials: "AH",
				url: "/user/alexis-haselberger/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/2108272_1035_5.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/2108272_1035_5.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/2108272_1035_5.jpg",
		published_title: "do-more-stress-less",
		tracking_id: "uGrNcVUJRTCLP-3g6ydcmQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Take control of your time, your to-do list, and your overwhelm.  Learn how to get it all done, without the stress.",
		num_subscribers: 126078,
		caption_locales: [
			{
				_class: "locale",
				locale: "bg_BG",
				title: "Български",
				english_title: "Bulgarian",
			},
			{
				_class: "locale",
				locale: "cs_CZ",
				title: "Čeština",
				english_title: "Czech",
			},
			{
				_class: "locale",
				locale: "da_DK",
				title: "Dansk",
				english_title: "Danish",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "el_GR",
				title: "Ελληνικά",
				english_title: "Greek",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "et_EE",
				title: "Eesti",
				english_title: "Estonian",
			},
			{
				_class: "locale",
				locale: "fi_FI",
				title: "Suomi",
				english_title: "Finnish",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "hu_HU",
				title: "Magyar",
				english_title: "Hungarian",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "ko_KR",
				title: "한국어",
				english_title: "Korean",
			},
			{
				_class: "locale",
				locale: "lt_LT",
				title: "Lietuvių",
				english_title: "Lithuanian",
			},
			{
				_class: "locale",
				locale: "lv_LV",
				title: "Latviešu",
				english_title: "Latvian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "sk_SK",
				title: "Slovenčina",
				english_title: "Slovak",
			},
			{
				_class: "locale",
				locale: "sv_SE",
				title: "Svenska",
				english_title: "Swedish",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "uk_UA",
				title: "Українська",
				english_title: "Ukrainian",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5471163,
		avg_rating_recent: 4.544641,
		rating: 4.544641,
		num_reviews: 51013,
		is_wishlisted: false,
		num_published_lectures: 45,
		num_published_practice_tests: 1,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/2108272_1035_5.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/2108272_1035_5.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/2108272_1035_5.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/2108272_1035_5.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [CC]",
			"Bulgarian [Auto]",
			"Czech [Auto]",
			"Danish [Auto]",
			"Dutch [Auto]",
			"Estonian [Auto]",
			"Finnish [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Greek [Auto]",
			"Hungarian [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Korean [Auto]",
			"Latvian [Auto]",
			"Lithuanian [Auto]",
			"Portuguese [Auto]",
			"Romanian [Auto]",
			"Simplified Chinese [Auto]",
			"Slovak [Auto]",
			"Spanish [Auto]",
			"Swedish [Auto]",
			"Thai [Auto]",
			"Ukrainian [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2018-12-26T17:41:09Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 12,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2019-04-11T17:04:22Z",
		objectives_summary: [
			"Discover and apply time-management and productivity strategies, techniques, and hacks",
			"Identify and solve for roadblocks that prevent you from being your most productive self",
			"Use your natural tendencies and traits to your advantage to optimize your time and productivity",
		],
		is_recently_published: false,
		last_update_date: "2023-03-10",
		preview_url: "/course/2108272/preview/",
		learn_url: "/course/do-more-stress-less/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: true,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "2 total hours",
		content_info_short: "2 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 8074,
				display_name: "Time Management",
				title: "Time Management",
				topic_channel_url: "/topic/time-management/",
				url: "/topic/time-management/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 591930,
		title: "Become a SuperLearner® 2: Learn Speed Reading & Boost Memory",
		url: "/course/become-a-superlearner-2-speed-reading-memory-accelerated-learning/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 1603568,
				title: "Jonathan Levi",
				name: "Jonathan",
				display_name: "Jonathan Levi",
				job_title:
					"Author, Top Instructor (>250K), Keynote Speaker, & Podcaster",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/1603568_4eb9_15.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/1603568_4eb9_15.jpg",
				initials: "JL",
				url: "/user/jonathanalevi/",
			},
			{
				_class: "user",
				id: 2334314,
				title: "Lev Goldentouch",
				name: "Lev",
				display_name: "Lev Goldentouch",
				job_title: "Accelerated learning and technology guru",
				image_50x50: "https://img-b.udemycdn.com/user/50x50/2334314_56fd_3.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/2334314_56fd_3.jpg",
				initials: "LG",
				url: "/user/levgold/",
			},
			{
				_class: "user",
				id: 2376580,
				title: "Anna Goldentouch",
				name: "Anna",
				display_name: "Anna Goldentouch",
				job_title: "Education guru",
				image_50x50: "https://img-b.udemycdn.com/user/50x50/2376580_9b51_6.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/2376580_9b51_6.jpg",
				initials: "AG",
				url: "/user/annagoldentouch/",
			},
			{
				_class: "user",
				id: 75469214,
				title: "SuperHuman Academy®",
				name: "SuperHuman",
				display_name: "SuperHuman Academy®",
				job_title: "Creator of some of the web's top personal growth products",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/75469214_38e1_2.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/75469214_38e1_2.jpg",
				initials: "SA",
				url: "/user/superhuman-academy/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/591930_e9a5_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/591930_e9a5_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/591930_e9a5_3.jpg",
		published_title:
			"become-a-superlearner-2-speed-reading-memory-accelerated-learning",
		tracking_id: "B6NiVE57TMC3IOG1CadDdQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"The original course to learn faster & more easily using the skills of the worlds fastest readers & memory record holders",
		num_subscribers: 218835,
		caption_locales: [
			{
				_class: "locale",
				locale: "ar_AR",
				title: "العربية",
				english_title: "Arabic",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5106635,
		avg_rating_recent: 4.493175,
		rating: 4.493175,
		num_reviews: 37638,
		is_wishlisted: false,
		num_published_lectures: 63,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/591930_e9a5_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/591930_e9a5_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/591930_e9a5_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/591930_e9a5_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Arabic [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
			"Turkish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2015-08-24T15:22:20Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2015-12-03T18:33:51Z",
		objectives_summary: [
			"Learn to read roughly 3 times the speed of an average college graduate, with above-average comprehension and retention",
			"Master the exact same skills that win World Championships in Memorization - skills that can teach you to memorize thousands of data points in order",
			"Learn how to process and internalize information in a highly-effective way, and how to apply this teaching to any skill you wish to learn",
		],
		is_recently_published: false,
		last_update_date: "2022-12-11",
		preview_url: "/course/591930/preview/",
		learn_url:
			"/course/become-a-superlearner-2-speed-reading-memory-accelerated-learning/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "5 total hours",
		content_info_short: "5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "32b24c8dfd2e439a829952fb6c5b8a97",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6506,
					display_name: "Learning Strategies",
					title: "Learning Strategies",
					topic_channel_url: "/topic/learning-strategies/",
					url: "/topic/learning-strategies/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "32b24c8dfd2e439a829952fb6c5b8a97",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6506,
						display_name: "Learning Strategies",
						title: "Learning Strategies",
						topic_channel_url: "/topic/learning-strategies/",
						url: "/topic/learning-strategies/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7840,
				display_name: "Speed Reading",
				title: "Speed Reading",
				topic_channel_url: "/topic/speed-reading/",
				url: "/topic/speed-reading/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1080376,
		title: "Life Coaching Certificate Course (Beginner to Intermediate)",
		url: "/course/life-coaching-online-certification-course-life-coach-training/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 3890126,
				title: "Kain Ramsay",
				name: "Kain",
				display_name: "Kain Ramsay",
				job_title:
					"Teacher of Modern Applied Psychology & Personal Development",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/3890126_2b28_17.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/3890126_2b28_17.jpg",
				initials: "KR",
				url: "/user/kainramsay/",
			},
			{
				_class: "user",
				id: 50670208,
				title: "The Academy of Modern Applied Psychology",
				name: "The Academy of Modern",
				display_name: "The Academy of Modern Applied Psychology",
				job_title:
					"Leading the Revolution in Online Applied Psychology Training",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/50670208_47f0_7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/50670208_47f0_7.jpg",
				initials: "TA",
				url: "/user/achology-ltd/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1080376_3647_10.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1080376_3647_10.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1080376_3647_10.jpg",
		published_title:
			"life-coaching-online-certification-course-life-coach-training",
		tracking_id: "TnxrcIjERi6CpaSeuY2uIQ",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"A comprehensive online training that delivers in-depth understanding of the key elements of the Life Coaching profession",
		num_subscribers: 152151,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
		],
		avg_rating: 4.6900587,
		avg_rating_recent: 4.690921,
		rating: 4.690921,
		num_reviews: 36182,
		is_wishlisted: false,
		num_published_lectures: 130,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1080376_3647_10.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1080376_3647_10.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1080376_3647_10.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1080376_3647_10.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"Inglês [Automático]",
			"Alemão [Automático]",
			"Espanhol [Automático]",
			"Francês [Automático]",
			"Indonésio [Automático]",
			"Italiano [Automático]",
		],
		created: "2017-01-17T22:38:10Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-03-11T03:58:33Z",
		objectives_summary: [
			"A time-proven life coaching methodology that’s been practiced on 2000+ people.",
			"Develop an enhanced sense of social awareness and improve your people skills.",
			"Lead people into heightened states of innovation, creativity and personal effectiveness.",
		],
		is_recently_published: false,
		last_update_date: "2022-10-17",
		preview_url: "/course/1080376/preview/",
		learn_url:
			"/course/life-coaching-online-certification-course-life-coach-training/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "33.5 total hours",
		content_info_short: "33.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 10684,
				display_name: "Life Coach Training",
				title: "Life Coach Training",
				topic_channel_url: "/topic/life-coaching/",
				url: "/topic/life-coaching/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1532040,
		title: "Productivity Machine: Time Management & Productivity Hacks",
		url: "/course/productivitymachine/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 17089836,
				title: "Patrick Dang",
				name: "Patrick",
				display_name: "Patrick Dang",
				job_title: "Entrepreneur | Sales Coach | Sales Legacy",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/17089836_22f0_8.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/17089836_22f0_8.jpg",
				initials: "PD",
				url: "/user/patrickdang/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1532040_12da_2.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1532040_12da_2.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1532040_12da_2.jpg",
		published_title: "productivitymachine",
		tracking_id: "RHDhuq2TQ6i-wVO9za6ETA",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Productivity & Time Management Strategies for Goal Setting, Eliminating Distractions, & Building Habits for Success.",
		num_subscribers: 57092,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.566778,
		avg_rating_recent: 4.5414906,
		rating: 4.5414906,
		num_reviews: 27563,
		is_wishlisted: false,
		num_published_lectures: 19,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1532040_12da_2.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1532040_12da_2.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1532040_12da_2.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1532040_12da_2.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [CC]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
		],
		created: "2018-01-30T03:51:26Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-03-01T23:29:32Z",
		objectives_summary: [
			"Students will learn the PROVEN Productivity Machine Methodology to get MORE done in LESS time",
			"The most effective way to manage your time in your personal and professional career",
			"How to set crystal clear goals and develop a step by step plan of execution",
		],
		is_recently_published: false,
		last_update_date: "2021-08-25",
		preview_url: "/course/1532040/preview/",
		learn_url: "/course/productivitymachine/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: true,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "2.5 total hours",
		content_info_short: "2.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7142,
				display_name: "Personal Productivity",
				title: "Personal Productivity",
				topic_channel_url: "/topic/personal-productivity/",
				url: "/topic/personal-productivity/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 941752,
		title: "Storytelling to Influence",
		url: "/course/storytellingtoinfluence/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 21198036,
				title: "Jeff Tan",
				name: "Jeff",
				display_name: "Jeff Tan",
				job_title: "Making It Happen as a Learning Innovator, Coach, & Speaker",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/21198036_c232.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/21198036_c232.jpg",
				initials: "JT",
				url: "/user/jeff-tan-2/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/941752_d931_5.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/941752_d931_5.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/941752_d931_5.jpg",
		published_title: "storytellingtoinfluence",
		tracking_id: "S2xl8lAHQXCEPdNtk4NmsA",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"How to use stories to influence decision makers in the audience!",
		num_subscribers: 58884,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ru_RU",
				title: "Русский",
				english_title: "Russian",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.389474,
		avg_rating_recent: 4.3572106,
		rating: 4.3572106,
		num_reviews: 26932,
		is_wishlisted: false,
		num_published_lectures: 24,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/941752_d931_5.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/941752_d931_5.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/941752_d931_5.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/941752_d931_5.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
			"Russian [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
		],
		created: "2016-08-26T09:23:38Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2016-09-02T17:33:17Z",
		objectives_summary: [
			"FIND new stories easily to add impact and emphasis to your message",
			"PRESENT your message clearly",
			"LEAD your audience step-by-step",
		],
		is_recently_published: false,
		last_update_date: "2023-06-09",
		preview_url: "/course/941752/preview/",
		learn_url: "/course/storytellingtoinfluence/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "42 total mins",
		content_info_short: "42 mins",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7910,
				display_name: "Storytelling",
				title: "Storytelling",
				topic_channel_url: "/topic/storytelling/",
				url: "/topic/storytelling/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1436164,
		title: "Customer Service: Soft Skills Fundamentals",
		url: "/course/customer-service-soft-skills-fundamentals/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 36775572,
				title: "Samara Wenten",
				name: "Samara",
				display_name: "Samara Wenten",
				job_title: "Customer Service Veteran",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/36775572_e8e2.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/36775572_e8e2.jpg",
				initials: "SW",
				url: "/user/samara-wenten/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1436164_3b76_2.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1436164_3b76_2.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1436164_3b76_2.jpg",
		published_title: "customer-service-soft-skills-fundamentals",
		tracking_id: "K1rKeLYpQyKYQRAXK2C09A",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline: "How to keep your head when everyone else is losing theirs",
		num_subscribers: 65366,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5580077,
		avg_rating_recent: 4.5170193,
		rating: 4.5170193,
		num_reviews: 26433,
		is_wishlisted: false,
		num_published_lectures: 22,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1436164_3b76_2.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1436164_3b76_2.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1436164_3b76_2.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1436164_3b76_2.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2017-11-17T00:00:43Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-12-07T23:36:12Z",
		objectives_summary: [
			"How to take care of yourself while taking care of others",
			"How to really listen to customers, not just hear their problems",
			"How to be personable even when you're not there in person",
		],
		is_recently_published: false,
		last_update_date: "2017-12-13",
		preview_url: "/course/1436164/preview/",
		learn_url: "/course/customer-service-soft-skills-fundamentals/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "40 total mins",
		content_info_short: "40 mins",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "ba23514fb4f54941861e02a4943905b4",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5312,
					display_name: "Customer Service",
					title: "Customer Service",
					topic_channel_url: "/topic/customer-service/",
					url: "/topic/customer-service/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "ba23514fb4f54941861e02a4943905b4",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5312,
						display_name: "Customer Service",
						title: "Customer Service",
						topic_channel_url: "/topic/customer-service/",
						url: "/topic/customer-service/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5312,
				display_name: "Customer Service",
				title: "Customer Service",
				topic_channel_url: "/topic/customer-service/",
				url: "/topic/customer-service/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 3475640,
		title: "Critical Thinking Strategies For Better Decisions",
		url: "/course/critical-thinking-strategies/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 380776,
				title: "John Rampton",
				name: "John",
				display_name: "John Rampton",
				job_title: "Entrepreneur",
				image_50x50: "https://img-b.udemycdn.com/user/50x50/380776_bcf2_3.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/380776_bcf2_3.jpg",
				initials: "JR",
				url: "/user/johnrampton/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/3475640_27f2_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/3475640_27f2_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/3475640_27f2_3.jpg",
		published_title: "critical-thinking-strategies",
		tracking_id: "TIKL2WWcTbaBn3QGkflQSw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Upgrade your problem solving skills and optimize business outcomes by applying the critical thinking process.",
		num_subscribers: 53877,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "ja_JP",
				title: "日本語",
				english_title: "Japanese",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.338819,
		avg_rating_recent: 4.3328876,
		rating: 4.3328876,
		num_reviews: 25638,
		is_wishlisted: false,
		num_published_lectures: 23,
		num_published_practice_tests: 1,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/3475640_27f2_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/3475640_27f2_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/3475640_27f2_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/3475640_27f2_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [CC]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Japanese [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
			"Turkish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2020-09-04T17:58:25Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 10,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2020-11-19T22:31:44Z",
		objectives_summary: [
			"Explore the concept of critical thinking, its value, and how it works.",
			"Discover what goes into critical thinking to create effective critical thinking.",
			"Determine what stands in the way of critical thinking and how to tear down these barriers.",
		],
		is_recently_published: false,
		last_update_date: "2020-12-16",
		preview_url: "/course/3475640/preview/",
		learn_url: "/course/critical-thinking-strategies/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: true,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1 total hour",
		content_info_short: "1 hour",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "c081844d58984578b7420e9f152c431b",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5292,
					display_name: "Critical Thinking",
					title: "Critical Thinking",
					topic_channel_url: "/topic/critical-thinking/",
					url: "/topic/critical-thinking/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "c081844d58984578b7420e9f152c431b",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5292,
						display_name: "Critical Thinking",
						title: "Critical Thinking",
						topic_channel_url: "/topic/critical-thinking/",
						url: "/topic/critical-thinking/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5292,
				display_name: "Critical Thinking",
				title: "Critical Thinking",
				topic_channel_url: "/topic/critical-thinking/",
				url: "/topic/critical-thinking/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1210442,
		title: "Psychology of Diversity and Unconscious Bias",
		url: "/course/psychology-diversity-unconscious-bias-discrimination/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 12056666,
				title: "Andrew Luttrell, Ph.D.",
				name: "Andrew",
				display_name: "Andrew Luttrell, Ph.D.",
				job_title: "Social Psychologist",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/12056666_002b_2.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/12056666_002b_2.jpg",
				initials: "AL",
				url: "/user/andrewluttrell/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1210442_2432.jpg",
		image_240x135: "https://img-c.udemycdn.com/course/240x135/1210442_2432.jpg",
		is_practice_test_course: false,
		image_480x270: "https://img-c.udemycdn.com/course/480x270/1210442_2432.jpg",
		published_title: "psychology-diversity-unconscious-bias-discrimination",
		tracking_id: "KGRx8xv8TAyVJ7h7klZdPw",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Understand Stereotypes, Prejudice, and Discrimination and How to Reduce Their Influence at Work and Your Community",
		num_subscribers: 55783,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.482636,
		avg_rating_recent: 4.4725156,
		rating: 4.4725156,
		num_reviews: 25617,
		is_wishlisted: false,
		num_published_lectures: 33,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1210442_2432.jpg",
		image_100x100: "https://img-c.udemycdn.com/course/100x100/1210442_2432.jpg",
		image_304x171: "https://img-c.udemycdn.com/course/304x171/1210442_2432.jpg",
		image_750x422: "https://img-c.udemycdn.com/course/750x422/1210442_2432.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [CC]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Romanian [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Turkish [Auto]",
		],
		created: "2017-05-09T19:28:31Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-05-16T23:55:10Z",
		objectives_summary: [
			"Understand the difference between stereotypes, prejudice, and discrimination.",
			"Identify acts of stereotyping.",
			"Develop the ideal mentality for engaging with an increasingly diverse society.",
		],
		is_recently_published: false,
		last_update_date: "2021-10-21",
		preview_url: "/course/1210442/preview/",
		learn_url:
			"/course/psychology-diversity-unconscious-bias-discrimination/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: true,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "2.5 total hours",
		content_info_short: "2.5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "fd43443cf67a4ed5a66790695484b6fc",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 9362,
					display_name: "Diversity and Inclusion",
					title: "Diversity and Inclusion",
					topic_channel_url: "/topic/diversity/",
					url: "/topic/diversity/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "fd43443cf67a4ed5a66790695484b6fc",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 9362,
						display_name: "Diversity and Inclusion",
						title: "Diversity and Inclusion",
						topic_channel_url: "/topic/diversity/",
						url: "/topic/diversity/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 9362,
				display_name: "Diversity and Inclusion",
				title: "Diversity and Inclusion",
				topic_channel_url: "/topic/diversity/",
				url: "/topic/diversity/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1336872,
		title: "Neuro-Linguistic Programming (NLP) Practitioner Certificate",
		url: "/course/nlp-practitioner-neuro-linguistic-programming-online-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 3890126,
				title: "Kain Ramsay",
				name: "Kain",
				display_name: "Kain Ramsay",
				job_title:
					"Teacher of Modern Applied Psychology & Personal Development",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/3890126_2b28_17.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/3890126_2b28_17.jpg",
				initials: "KR",
				url: "/user/kainramsay/",
			},
			{
				_class: "user",
				id: 50670208,
				title: "The Academy of Modern Applied Psychology",
				name: "The Academy of Modern",
				display_name: "The Academy of Modern Applied Psychology",
				job_title:
					"Leading the Revolution in Online Applied Psychology Training",
				image_50x50:
					"https://img-c.udemycdn.com/user/50x50/50670208_47f0_7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/50670208_47f0_7.jpg",
				initials: "TA",
				url: "/user/achology-ltd/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1336872_db4d_7.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1336872_db4d_7.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1336872_db4d_7.jpg",
		published_title:
			"nlp-practitioner-neuro-linguistic-programming-online-course",
		tracking_id: "54466ciPQIWSDT6Dm7CHZg",
		locale: {
			_class: "locale",
			locale: "en_GB",
			title: "English (UK)",
			english_title: "English (UK)",
			simple_english_title: "English",
		},
		headline:
			"Gain an in-depth understanding of Neuro-Linguistic Programming (NLP) for personal growth and professional excellence.",
		num_subscribers: 133872,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_GB",
				title: "English (UK)",
				english_title: "English (UK)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
		],
		avg_rating: 4.60066,
		avg_rating_recent: 4.6032686,
		rating: 4.6032686,
		num_reviews: 24387,
		is_wishlisted: false,
		num_published_lectures: 155,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1336872_db4d_7.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1336872_db4d_7.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1336872_db4d_7.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1336872_db4d_7.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Italian [Auto]",
			"Spanish [Auto]",
		],
		created: "2017-08-31T16:14:17Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-10-09T16:23:41Z",
		objectives_summary: [
			"The conscious use of language – Milton & Meta model approaches.",
			"Know how the mind works – the processes and the programming.",
			"Take complete control of your thinking with the power of Anchoring.",
		],
		is_recently_published: false,
		last_update_date: "2022-10-17",
		preview_url: "/course/1336872/preview/",
		learn_url:
			"/course/nlp-practitioner-neuro-linguistic-programming-online-course/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "42 total hours",
		content_info_short: "42 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "f79a75b4d11b44a6aee398357f31396d",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 6910,
					display_name: "Neuro-Linguistic Programming",
					title: "Neuro-Linguistic Programming",
					topic_channel_url: "/topic/neuro-linguistic-programming/",
					url: "/topic/neuro-linguistic-programming/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "f79a75b4d11b44a6aee398357f31396d",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 6910,
						display_name: "Neuro-Linguistic Programming",
						title: "Neuro-Linguistic Programming",
						topic_channel_url: "/topic/neuro-linguistic-programming/",
						url: "/topic/neuro-linguistic-programming/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 6910,
				display_name: "Neuro-Linguistic Programming",
				title: "Neuro-Linguistic Programming",
				topic_channel_url: "/topic/neuro-linguistic-programming/",
				url: "/topic/neuro-linguistic-programming/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 466736,
		title: "Stress Management: 40+ easy ways to deal with stress",
		url: "/course/stress-management-40-easy-ways-to-deal-with-stress/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 7010472,
				title: "Gregory Caremans - Brain Academy",
				name: "Gregory Caremans -",
				display_name: "Gregory Caremans - Brain Academy",
				job_title: "Neurocognitive and Behavioral Expert",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/7010472_fcc1_6.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/7010472_fcc1_6.jpg",
				initials: "GB",
				url: "/user/gregorycaremans/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/466736_d5f4_6.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/466736_d5f4_6.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/466736_d5f4_6.jpg",
		published_title: "stress-management-40-easy-ways-to-deal-with-stress",
		tracking_id: "sx-sXdYQTpu4O-izLB4pTg",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Stress relief and burnout prevention. Don't let stress control your life. Beat anxiety and worries. Live, Laugh, Love.",
		num_subscribers: 71637,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5077972,
		avg_rating_recent: 4.499377,
		rating: 4.499377,
		num_reviews: 23100,
		is_wishlisted: false,
		num_published_lectures: 20,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/466736_d5f4_6.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/466736_d5f4_6.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/466736_d5f4_6.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/466736_d5f4_6.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
		],
		created: "2015-04-03T16:21:39Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2015-07-08T23:56:31Z",
		objectives_summary: [
			"Understand the different types of stress",
			"Understand the different types of relief strategies",
			"Apply over 40 different ways to manage your stress ",
		],
		is_recently_published: false,
		last_update_date: "2023-04-28",
		preview_url: "/course/466736/preview/",
		learn_url:
			"/course/stress-management-40-easy-ways-to-deal-with-stress/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1 total hour",
		content_info_short: "1 hour",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "116d8b4f14bb4efa862a0486b281e08e",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 7920,
					display_name: "Stress Management",
					title: "Stress Management",
					topic_channel_url: "/topic/stress-management/",
					url: "/topic/stress-management/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "116d8b4f14bb4efa862a0486b281e08e",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 7920,
						display_name: "Stress Management",
						title: "Stress Management",
						topic_channel_url: "/topic/stress-management/",
						url: "/topic/stress-management/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 7920,
				display_name: "Stress Management",
				title: "Stress Management",
				topic_channel_url: "/topic/stress-management/",
				url: "/topic/stress-management/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1432454,
		title: "Effective Email Communication: Enhancing Your Voice at Work",
		url: "/course/effective-email-communication/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 32892040,
				title: "Anonymized User",
				name: "Anonymized",
				display_name: "Anonymized User",
				job_title: "",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/anonymous_3.png",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/anonymous_3.png",
				initials: "AU",
				url: "",
			},
			{
				_class: "user",
				id: 32741038,
				title: "Nikki Woodford",
				name: "Nikki",
				display_name: "Nikki Woodford",
				job_title: "Education and Innovation Specialist",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/32741038_bb38.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/32741038_bb38.jpg",
				initials: "NW",
				url: "/user/nikki-woodford/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1432454_926b_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1432454_926b_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1432454_926b_4.jpg",
		published_title: "effective-email-communication",
		tracking_id: "yKC2dnEYRzG8QV40EULMnQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Improving the Clarity and Effectiveness of Digital Communication",
		num_subscribers: 57436,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.2562723,
		avg_rating_recent: 4.2354007,
		rating: 4.2354007,
		num_reviews: 23034,
		is_wishlisted: false,
		num_published_lectures: 11,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1432454_926b_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1432454_926b_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1432454_926b_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1432454_926b_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2017-11-14T03:01:44Z",
		instructional_level: "Beginner Level",
		instructional_level_simple: "Beginner",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2018-01-03T17:20:27Z",
		objectives_summary: [
			"Understand the nature of email communication",
			"Understand the importance of knowing intended audience",
			"Know appropriate structures for email messages",
		],
		is_recently_published: false,
		last_update_date: "2017-12-26",
		preview_url: "/course/1432454/preview/",
		learn_url: "/course/effective-email-communication/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "37 total mins",
		content_info_short: "37 mins",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5584,
				display_name: "Email Writing and Etiquette",
				title: "Email Writing and Etiquette",
				topic_channel_url: "/topic/email-etiquette/",
				url: "/topic/email-etiquette/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 363274,
		title: "Workplace Communication: You Can Speak Up at Meetings!",
		url: "/course/how-to-speak-up-at-meetings/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 2565950,
				title: "TJ Walker",
				name: "TJ",
				display_name: "TJ Walker",
				job_title: "BestSelling Personal Development & Habits Expert",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/2565950_892c_2.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/2565950_892c_2.jpg",
				initials: "TW",
				url: "/user/tjwalker2/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/363274_6346_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/363274_6346_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/363274_6346_4.jpg",
		published_title: "how-to-speak-up-at-meetings",
		tracking_id: "fcTO52LMQ2aRDXCMHDv82A",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"You Can Learn to Speak up At Anytime Knowing how To Look and Sound Your Best in Meetings",
		num_subscribers: 81297,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5741735,
		avg_rating_recent: 4.56542,
		rating: 4.56542,
		num_reviews: 22539,
		is_wishlisted: false,
		num_published_lectures: 610,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/363274_6346_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/363274_6346_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/363274_6346_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/363274_6346_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Dutch [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2014-12-04T19:17:23Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2014-12-11T16:45:25Z",
		objectives_summary: [
			"Speak up at meetings",
			"Project confidence when speaking in front of others",
			"Gather your thoughts quickly in order to offer impromptu comments",
		],
		is_recently_published: false,
		last_update_date: "2023-05-15",
		preview_url: "/course/363274/preview/",
		learn_url: "/course/how-to-speak-up-at-meetings/learn/",
		is_in_personal_plan_collection: false,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "29 total hours",
		content_info_short: "29 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "6f492de149994951a90dc2163192e900",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 9498,
					display_name: "Meetings",
					title: "Meetings",
					topic_channel_url: "/topic/meetings/",
					url: "/topic/meetings/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "6f492de149994951a90dc2163192e900",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 9498,
						display_name: "Meetings",
						title: "Meetings",
						topic_channel_url: "/topic/meetings/",
						url: "/topic/meetings/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 9498,
				display_name: "Meetings",
				title: "Meetings",
				topic_channel_url: "/topic/meetings/",
				url: "/topic/meetings/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 1350272,
		title: "Goal Setting Mastery Course",
		url: "/course/goal-setting-mastery-course/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 11913992,
				title: "Himesh Trivedi",
				name: "Himesh",
				display_name: "Himesh Trivedi",
				job_title: "Instructor, Coach, Speaker and Trainer",
				image_50x50:
					"https://img-b.udemycdn.com/user/50x50/11913992_ef88_2.jpg",
				image_100x100:
					"https://img-b.udemycdn.com/user/100x100/11913992_ef88_2.jpg",
				initials: "HT",
				url: "/user/himeshtrivedi/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/1350272_45ed_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/1350272_45ed_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/1350272_45ed_4.jpg",
		published_title: "goal-setting-mastery-course",
		tracking_id: "p-qJAS4MTDSnL3TSUneXew",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Define your WHY and align it to your goals & create a step by step blueprint to plan, implement & achieve your goals",
		num_subscribers: 38247,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5206695,
		avg_rating_recent: 4.4989066,
		rating: 4.4989066,
		num_reviews: 22185,
		is_wishlisted: false,
		num_published_lectures: 26,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/1350272_45ed_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/1350272_45ed_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/1350272_45ed_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/1350272_45ed_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Romanian [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Turkish [Auto]",
		],
		created: "2017-09-14T07:30:57Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2017-09-19T21:43:15Z",
		objectives_summary: [
			"Get clear direction on what you want out of life",
			"Setting SMARTER goals",
			"Have a specified action plan to achieve your goals incorporated into your daily routine",
		],
		is_recently_published: false,
		last_update_date: "2021-11-08",
		preview_url: "/course/1350272/preview/",
		learn_url: "/course/goal-setting-mastery-course/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1.5 total hours",
		content_info_short: "1.5 hours",
		bestseller_badge_content: null,
		badges: [],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5970,
				display_name: "Goal Setting",
				title: "Goal Setting",
				topic_channel_url: "/topic/goal-setting/",
				url: "/topic/goal-setting/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 989196,
		title: "SELF-CONFIDENCE: 40-minute Confidence & Self Esteem Guide",
		url: "/course/self-confidence-40-minute-confidence-self-esteem-guide/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 1859852,
				title: "Jimmy Naraine • 380,000+ Students",
				name: "Jimmy",
				display_name: "Jimmy Naraine • 380,000+ Students",
				job_title: "Top-Rated Udemy Partner with 76,000+ 5* Reviews",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/1859852_905a_7.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/1859852_905a_7.jpg",
				initials: "JN",
				url: "/user/jimmynaraine/",
			},
			{
				_class: "user",
				id: 137189967,
				title: "Jimmy Naraine Support",
				name: "Jimmy Naraine",
				display_name: "Jimmy Naraine Support",
				job_title: "Winner of Udemy Innovation Award teaching 223,000+ people",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/137189967_d1af.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/137189967_d1af.jpg",
				initials: "JS",
				url: "/user/jimmy-naraine-support/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/989196_01e2_3.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/989196_01e2_3.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/989196_01e2_3.jpg",
		published_title: "self-confidence-40-minute-confidence-self-esteem-guide",
		tracking_id: "5XiBj7h0Qo-VhIkuVOjJCQ",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"4h of NEW Content! Boost Your Confidence & Self Esteem, Handle Fear of Rejection,Learn Powerful Body Language,Feel Great",
		num_subscribers: 82174,
		caption_locales: [
			{
				_class: "locale",
				locale: "bg_BG",
				title: "Български",
				english_title: "Bulgarian",
			},
			{
				_class: "locale",
				locale: "cs_CZ",
				title: "Čeština",
				english_title: "Czech",
			},
			{
				_class: "locale",
				locale: "da_DK",
				title: "Dansk",
				english_title: "Danish",
			},
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "el_GR",
				title: "Ελληνικά",
				english_title: "Greek",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "et_EE",
				title: "Eesti",
				english_title: "Estonian",
			},
			{
				_class: "locale",
				locale: "fi_FI",
				title: "Suomi",
				english_title: "Finnish",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "hu_HU",
				title: "Magyar",
				english_title: "Hungarian",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "lt_LT",
				title: "Lietuvių",
				english_title: "Lithuanian",
			},
			{
				_class: "locale",
				locale: "lv_LV",
				title: "Latviešu",
				english_title: "Latvian",
			},
			{
				_class: "locale",
				locale: "nl_NL",
				title: "Nederlands",
				english_title: "Dutch",
			},
			{
				_class: "locale",
				locale: "pl_PL",
				title: "Polski",
				english_title: "Polish",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "ro_RO",
				title: "Română",
				english_title: "Romanian",
			},
			{
				_class: "locale",
				locale: "sk_SK",
				title: "Slovenčina",
				english_title: "Slovak",
			},
			{
				_class: "locale",
				locale: "sv_SE",
				title: "Svenska",
				english_title: "Swedish",
			},
			{
				_class: "locale",
				locale: "uk_UA",
				title: "Українська",
				english_title: "Ukrainian",
			},
			{
				_class: "locale",
				locale: "vi_VN",
				title: "Tiếng Việt",
				english_title: "Vietnamese",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.610642,
		avg_rating_recent: 4.5990562,
		rating: 4.5990562,
		num_reviews: 21571,
		is_wishlisted: false,
		num_published_lectures: 45,
		num_published_practice_tests: 0,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/989196_01e2_3.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/989196_01e2_3.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/989196_01e2_3.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/989196_01e2_3.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [Auto]",
			"Bulgarian [Auto]",
			"Czech [Auto]",
			"Danish [Auto]",
			"Dutch [Auto]",
			"Estonian [Auto]",
			"Finnish [Auto]",
			"French [Auto]",
			"German [Auto]",
			"Greek [Auto]",
			"Hungarian [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Latvian [Auto]",
			"Lithuanian [Auto]",
			"Polish [Auto]",
			"Portuguese [Auto]",
			"Romanian [Auto]",
			"Simplified Chinese [Auto]",
			"Slovak [Auto]",
			"Spanish [Auto]",
			"Swedish [Auto]",
			"Ukrainian [Auto]",
			"Vietnamese [Auto]",
		],
		created: "2016-10-20T05:00:48Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 0,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2016-11-01T05:07:53Z",
		objectives_summary: [
			"TOP-RATED Confidence Course (18,000+ 5/5 reviews)",
			"Last Content Update October 2022",
			"Comprehensive Downloadable PDF Summary of Each Lecture Attached!",
		],
		is_recently_published: false,
		last_update_date: "2022-12-30",
		preview_url: "/course/989196/preview/",
		learn_url:
			"/course/self-confidence-40-minute-confidence-self-esteem-guide/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: false,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "5 total hours",
		content_info_short: "5 hours",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "e6770fb2751842f98427c8c3fc537290",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 5202,
					display_name: "Confidence",
					title: "Confidence",
					topic_channel_url: "/topic/confidence/",
					url: "/topic/confidence/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "e6770fb2751842f98427c8c3fc537290",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 5202,
						display_name: "Confidence",
						title: "Confidence",
						topic_channel_url: "/topic/confidence/",
						url: "/topic/confidence/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 5202,
				display_name: "Confidence",
				title: "Confidence",
				topic_channel_url: "/topic/confidence/",
				url: "/topic/confidence/",
				tracking_object_type: "cl",
			},
		},
	},
	{
		_class: "course",
		id: 2787956,
		title: "Growth Mindset: The Key to Confidence, Impact & Fulfillment",
		url: "/course/growth-mindset-the-key-to-greater-confidence-and-impact/",
		is_paid: true,
		visible_instructors: [
			{
				_class: "user",
				id: 31246304,
				title: "Diane Flynn",
				name: "Diane",
				display_name: "Diane Flynn",
				job_title: "Co-founder and CEO of ReBoot Accel | Executive Coach",
				image_50x50: "https://img-c.udemycdn.com/user/50x50/31246304_d0a8.jpg",
				image_100x100:
					"https://img-c.udemycdn.com/user/100x100/31246304_d0a8.jpg",
				initials: "DF",
				url: "/user/diane-flynn-2/",
			},
		],
		image_125_H: "https://img-c.udemycdn.com/course/125_H/2787956_f2a8_4.jpg",
		image_240x135:
			"https://img-c.udemycdn.com/course/240x135/2787956_f2a8_4.jpg",
		is_practice_test_course: false,
		image_480x270:
			"https://img-c.udemycdn.com/course/480x270/2787956_f2a8_4.jpg",
		published_title: "growth-mindset-the-key-to-greater-confidence-and-impact",
		tracking_id: "4N3nFT2aSW-boXO69PvK6A",
		locale: {
			_class: "locale",
			locale: "en_US",
			title: "English (US)",
			english_title: "English (US)",
			simple_english_title: "English",
		},
		headline:
			"Discover how your mindset can expand possibilities and fulfillment, in your career and in life! Certification available",
		num_subscribers: 50999,
		caption_locales: [
			{
				_class: "locale",
				locale: "de_DE",
				title: "Deutsch",
				english_title: "German",
			},
			{
				_class: "locale",
				locale: "en_US",
				title: "English (US)",
				english_title: "English (US)",
			},
			{
				_class: "locale",
				locale: "es_ES",
				title: "Español (España)",
				english_title: "Spanish (Spain)",
			},
			{
				_class: "locale",
				locale: "fr_FR",
				title: "Français (France)",
				english_title: "French (France)",
			},
			{
				_class: "locale",
				locale: "id_ID",
				title: "Bahasa Indonesia",
				english_title: "Indonesian",
			},
			{
				_class: "locale",
				locale: "it_IT",
				title: "Italiano",
				english_title: "Italian",
			},
			{
				_class: "locale",
				locale: "ja_JP",
				title: "日本語",
				english_title: "Japanese",
			},
			{
				_class: "locale",
				locale: "ko_KR",
				title: "한국어",
				english_title: "Korean",
			},
			{
				_class: "locale",
				locale: "pt_BR",
				title: "Português (Brasil)",
				english_title: "Portuguese (Brazil)",
			},
			{
				_class: "locale",
				locale: "th_TH",
				title: "ภาษาไทย",
				english_title: "Thai",
			},
			{
				_class: "locale",
				locale: "tr_TR",
				title: "Türkçe",
				english_title: "Turkish",
			},
			{
				_class: "locale",
				locale: "zh_CN",
				title: "中文(简体)",
				english_title: "Simplified Chinese (China)",
			},
		],
		avg_rating: 4.5148797,
		avg_rating_recent: 4.4963365,
		rating: 4.4963365,
		num_reviews: 21320,
		is_wishlisted: false,
		num_published_lectures: 20,
		num_published_practice_tests: 1,
		image_50x50: "https://img-c.udemycdn.com/course/50x50/2787956_f2a8_4.jpg",
		image_100x100:
			"https://img-c.udemycdn.com/course/100x100/2787956_f2a8_4.jpg",
		image_304x171:
			"https://img-c.udemycdn.com/course/304x171/2787956_f2a8_4.jpg",
		image_750x422:
			"https://img-c.udemycdn.com/course/750x422/2787956_f2a8_4.jpg",
		is_in_user_subscription: false,
		has_closed_caption: true,
		caption_languages: [
			"English [CC]",
			"French [Auto]",
			"German [Auto]",
			"Indonesian [Auto]",
			"Italian [Auto]",
			"Japanese [Auto]",
			"Korean [Auto]",
			"Portuguese [Auto]",
			"Simplified Chinese [Auto]",
			"Spanish [Auto]",
			"Thai [Auto]",
			"Turkish [Auto]",
		],
		created: "2020-01-30T17:43:04Z",
		instructional_level: "All Levels",
		instructional_level_simple: "All Levels",
		content_length_practice_test_questions: 10,
		is_user_subscribed: false,
		buyable_object_type: "course",
		published_time: "2020-03-06T22:56:06Z",
		objectives_summary: [
			"Discover how growth mindset can propel your confidence and career, while making you more innovative and willing to take risks",
			"Identify when you’re showing up with a fixed mindset, and how this might be holding you back at work and in life",
			"Consider 6 roadblocks that may be keeping you from having a growth mindset, along with proven strategies to overcome them",
		],
		is_recently_published: false,
		last_update_date: "2023-05-27",
		preview_url: "/course/2787956/preview/",
		learn_url:
			"/course/growth-mindset-the-key-to-greater-confidence-and-impact/learn/",
		is_in_personal_plan_collection: true,
		is_in_premium: false,
		has_508_closed_captions: true,
		is_coding_exercises_badge_eligible: false,
		predictive_score: null,
		relevancy_score: null,
		input_features: null,
		lecture_search_result: null,
		curriculum_lectures: [],
		order_in_results: null,
		curriculum_items: [],
		instructor_name: null,
		content_info: "1 total hour",
		content_info_short: "1 hour",
		bestseller_badge_content: {
			_class: "ds_course_badge",
			id: "c5aa5b403aff4147a4d6d9aaf1344c9a",
			badge_text: "Bestseller",
			badge_family: "bestseller",
			context_info: {
				category: {
					id: 296,
					title: "Personal Development",
					url: "/courses/personal-development/",
					tracking_object_type: "cat",
				},
				subcategory: null,
				label: {
					id: 155648,
					display_name: "Growth Mindset",
					title: "Growth Mindset",
					topic_channel_url: "/topic/growth-mindset/",
					url: "/topic/growth-mindset/",
					tracking_object_type: "cl",
				},
			},
		},
		badges: [
			{
				_class: "ds_course_badge",
				id: "c5aa5b403aff4147a4d6d9aaf1344c9a",
				badge_text: "Bestseller",
				badge_family: "bestseller",
				context_info: {
					category: {
						id: 296,
						title: "Personal Development",
						url: "/courses/personal-development/",
						tracking_object_type: "cat",
					},
					subcategory: null,
					label: {
						id: 155648,
						display_name: "Growth Mindset",
						title: "Growth Mindset",
						topic_channel_url: "/topic/growth-mindset/",
						url: "/topic/growth-mindset/",
						tracking_object_type: "cl",
					},
				},
			},
		],
		free_course_subscribe_url: null,
		context_info: {
			category: {
				id: 296,
				title: "Personal Development",
				url: "/courses/personal-development/",
				tracking_object_type: "cat",
			},
			subcategory: null,
			label: {
				id: 155648,
				display_name: "Growth Mindset",
				title: "Growth Mindset",
				topic_channel_url: "/topic/growth-mindset/",
				url: "/topic/growth-mindset/",
				tracking_object_type: "cl",
			},
		},
	},
];
